-- ============================================================================
-- Core job table
-- ============================================================================
CREATE TABLE jorb (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue           TEXT        NOT NULL DEFAULT 'default',
    capability      TEXT,                 -- worker must advertise this to claim
    prio            INTEGER     NOT NULL DEFAULT 100,  -- lower = more urgent
    state           jorbstate   NOT NULL DEFAULT 'queued',
    job_class       TEXT        NOT NULL,
    kwargs          JSONB       NOT NULL DEFAULT '{}',
    admin_data      JSONB       NOT NULL DEFAULT '{}',
    result          JSONB,
    uid             BIGINT,               -- multi-tenancy tag
    tags            JSONB       NOT NULL DEFAULT '{}',  -- caller's own labels

    -- dependency edges
    run_group       BIGINT,
    waitfor_group   BIGINT,
    waitfor_job     BIGINT,
    dag_id          BIGINT,

    -- idempotent enqueue: one queued row per (deadline_key, queue)
    deadline_key    TEXT,

    -- provenance: the recurring schedule that fired this job into existence
    schedule_id     BIGINT,

    -- execution bookkeeping
    run_count       INTEGER     NOT NULL DEFAULT 0,
    error_count     INTEGER     NOT NULL DEFAULT 0,
    error_message   TEXT,
    error_backtrace TEXT,
    run_epoch       INTEGER     NOT NULL DEFAULT 0,  -- fencing token (see COMMENT)
    cancel_requested BOOLEAN    NOT NULL DEFAULT FALSE,
    -- demand latch for the jorb_done / jorb_event channels (see the
    -- notification section at the bottom of this file)
    awaited         BOOLEAN     NOT NULL DEFAULT FALSE,

    -- who has it
    claimed_by      BIGINT,               -- jorb_worker.id
    worker_pid      INTEGER,
    worker_host     TEXT,

    -- timing (all timestamptz)
    created         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated         TIMESTAMPTZ NOT NULL DEFAULT now(),
    run_after       TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at      TIMESTAMPTZ,
    started         TIMESTAMPTZ,
    finished        TIMESTAMPTZ,
    timeout_at      TIMESTAMPTZ
);

COMMENT ON TABLE jorb IS 'Jobs. One row per job for its whole life; retries re-queue the same row.';
COMMENT ON COLUMN jorb.prio IS 'Lower numbers are more urgent; workers claim jobs with prio <= their ceiling.';
COMMENT ON COLUMN jorb.claimed_at IS 'When this attempt was admitted by a worker. Rate limits count admissions, not execution starts: started is written after the claim commits, so counting it lets a claim miss the claim before it.';
COMMENT ON COLUMN jorb.run_epoch IS 'Fencing token, NOT an attempt counter (that is run_count). Advances whenever the job enters an attempt (claim) or leaves one (finish, crash, cancel, retry, requeue, reschedule), so an execution the row has moved past may not write results, checkpoints, events, or mailbox messages.';
COMMENT ON COLUMN jorb.awaited IS 'Someone has waited on this job (wait_for_result/get_event). Set by the waiter BEFORE it looks at the state, and never cleared: it is the demand signal that switches the jorb_done and jorb_event notifications on for this job, and it costs one HOT update per job that is ever awaited.';
COMMENT ON COLUMN jorb.tags IS 'The CALLER''s labels (customer, region, batch), flat key -> scalar, for filtering jobs by something the application means. Deliberately NOT admin_data: that column is the platform''s own execution config (max_retries, timeout_seconds, save_result, schedule metadata), which nobody filters on, so indexing it would tax every enqueue to make no query faster. The one thing anybody DID filter admin_data by is now jorb.schedule_id: a fact worth querying by is worth a column, because the alternative is an expression index over a jsonb blob written by every job to answer a question asked about a handful of them.';
COMMENT ON COLUMN jorb.waitfor_group IS 'Becomes queued only when ALL jobs with run_group = this value are finished.';
COMMENT ON COLUMN jorb.waitfor_job IS 'Becomes queued only when the job with this id is finished.';
COMMENT ON COLUMN jorb.schedule_id IS 'The jorb_schedule row that fired this job, NULL for every job enqueued directly. This is the SOLE source of that fact -- it used to live in admin_data->>''schedule_id'', which no index could serve, so the scheduler''s max_concurrent_jobs check scanned the whole job table on every firing. Deliberately NOT a foreign key: jobs outlive the schedules that made them (deleting a schedule must not delete or rewrite its history), and a REFERENCES here would need an index over EVERY schedule-created job to serve the cascade, undoing the point of the partial index below.';

-- the poll/claim path
CREATE INDEX jorb_claim_idx ON jorb (queue, prio, run_after)
    WHERE state = 'queued';
-- rate limiting counts recent admissions per queue
CREATE INDEX jorb_claimed_at_idx ON jorb (queue, claimed_at)
    WHERE claimed_at IS NOT NULL;
-- duration/throughput reporting
CREATE INDEX jorb_started_idx ON jorb (queue, started)
    WHERE started IS NOT NULL;
-- reaper scans
CREATE INDEX jorb_inflight_idx ON jorb (state, updated)
    WHERE state IN ('claimed', 'running');
-- retention: the sweep asks "which terminal jobs aged out?" every cycle, and
-- once it has caught up the honest answer is usually "none". Without this it
-- reads the whole terminal backlog to say so -- measured at 300k rows that is
-- already a full scan, and a busy install keeps orders of magnitude more.
-- Indexed on the expression the sweep actually filters by.
CREATE INDEX jorb_retention_idx ON jorb (COALESCE(finished, updated))
    WHERE state IN ('finished', 'crashed', 'cancelled');
-- checkpoint retention is a SEPARATE, shorter window and a NARROWER state
-- set: only 'finished' jobs have their checkpoints reaped early, because
-- 'crashed'/'cancelled' are retryable and a retry resumes from checkpoints.
-- A dedicated partial index keeps that sweep from walking past (and
-- discarding) the crashed/cancelled terminal rows the all-terminal index
-- above would hand it -- on a crash-heavy install that discard is otherwise
-- proportional to the terminal backlog.
CREATE INDEX jorb_finished_retention_idx ON jorb (COALESCE(finished, updated))
    WHERE state = 'finished';
-- reporting windows. Deliberately on `created` and NOT on `updated`:
-- `updated` is rewritten by every state change, so indexing it would add an
-- index write to each of the ~4 updates per job AND block HOT updates on the
-- hottest table in the system -- paying in permanent bloat for a read that
-- happens on a scrape interval. `created` is written once.
CREATE INDEX jorb_created_idx ON jorb (created);
CREATE INDEX jorb_timeout_idx ON jorb (timeout_at)
    WHERE state = 'running' AND timeout_at IS NOT NULL;
-- dependency wakeups
CREATE INDEX jorb_waitfor_job_idx   ON jorb (waitfor_job)   WHERE state = 'waiting';
CREATE INDEX jorb_waitfor_group_idx ON jorb (waitfor_group) WHERE state = 'waiting';
-- Partial like their neighbours, and for the same reason: run_group and uid
-- are NULL on the overwhelming majority of jobs (only grouped work and
-- multi-tenant callers set them), but a plain btree indexes NULLs too. That
-- means an index entry written on every insert and maintained by every
-- vacuum, for rows the index can never usefully answer a question about --
-- pure write amplification on the hottest table in the system.
CREATE INDEX jorb_run_group_idx ON jorb (run_group) WHERE run_group IS NOT NULL;
-- The group-wake gate ("is any member still unfinished?") runs on the
-- completion path of EVERY grouped job. Its NOT EXISTS probe wants one
-- unfinished witness; over jorb_run_group_idx it walks past finished members
-- to find one, an O(members) tail exactly when the group nears completion.
-- This index holds only the unfinished members, so the probe is O(1) at any
-- group size -- and it SHRINKS to empty as groups finish, so its steady-state
-- write cost is bounded by grouped work in flight, not by group history.
CREATE INDEX jorb_group_unfinished_idx ON jorb (run_group)
    WHERE run_group IS NOT NULL AND state != 'finished';
CREATE INDEX jorb_uid_idx       ON jorb (uid)       WHERE uid IS NOT NULL;
CREATE INDEX jorb_dag_idx           ON jorb (dag_id) WHERE dag_id IS NOT NULL;
-- Caller-supplied labels, and partial for exactly the reason the three above
-- are: almost every job sets no tags at all, and a plain GIN index would
-- still store an entry for each of them -- an object with no keys yields no
-- keys to index, so GIN records it as an empty item purely so that a full
-- index scan can find the row again. That is write amplification on the
-- hottest table in the system in exchange for nothing.
--
-- The predicate keeps the untagged enqueue path -- the hot one -- out of the
-- index entirely, and that is measured, not assumed. At 16 concurrent
-- connections with one transaction per job, untagged enqueue is unchanged by
-- this index existing (28.7k vs 28.9k jobs/s, medians of nine interleaved
-- pj-bench pairs, which is noise on a shared box). Enqueue WITH tags
-- populated measures 0.93-1.04x of untagged even when every job carries a
-- DISTINCT tag value, GIN's pessimal case: fastupdate parks new entries in
-- the pending list and the merge is autovacuum's problem, not the enqueuing
-- transaction's. tests/test_job_tags.py holds both measurements, and asserts
-- the index does not grow at all when 10,000 untagged jobs are inserted.
--
-- THE COST OF PARTIAL, which every caller has to pay attention to: a query
-- may use a partial index only when its own clauses IMPLY the predicate, and
-- PostgreSQL proves that syntactically. It cannot derive `tags <> '{}'` from
-- `tags @> '{"customer":"acme"}'`, so a filter that omits the predicate is
-- correct and sequentially scans the table. Every tag filter in this codebase
-- is therefore built by client.tags_filter_sql, which emits both clauses.
CREATE INDEX jorb_tags_idx ON jorb USING GIN (tags) WHERE tags <> '{}';
-- The scheduler's max_concurrent_jobs check: "how many of MY jobs are still
-- in flight?", asked once per firing of every schedule. Partial on BOTH
-- clauses, and each one is doing separate work.
--
--   schedule_id IS NOT NULL keeps the overwhelming majority of jobs -- every
--   one a client enqueued -- out of the index entirely, so the hot enqueue
--   path evaluates a null check and writes nothing. Same trade as
--   jorb_run_group_idx, jorb_uid_idx and jorb_tags_idx above, and measured
--   the same way: 27,941 vs 28,010 jobs/s across nine INTERLEAVED
--   `pj-bench enqueue --concurrency 16 --repeat 3` pairs, which is no
--   difference at all against a within-run spread of 10-33%
--   (docs/RECURRING_SCHEDULER.md#performance carries the numbers, and
--   tests/test_scale_plans.py asserts the index does not grow by one page
--   when 20,000 client-enqueued jobs are inserted).
--
--   state IN (...) is what stops this becoming the very problem it fixes. A
--   schedule accumulates jobs forever -- a minutely one writes ~525k a year --
--   so an index on schedule_id alone would hand the check every job the
--   schedule has EVER created and make it discard the terminal ones. That
--   costs a scan and passes a no-seq-scan check, which is exactly the failure
--   tests/utils/plans.rows_removed_by_filter exists to catch. Restricted to
--   the live states the index holds only in-flight work, which the limit
--   itself bounds: the check's cost tracks the schedule's own concurrency and
--   not the age of the install.
--
-- state is already a predicate column of jorb_claim_idx, jorb_inflight_idx
-- and jorb_retention_idx, so the transitions that move a row in and out of
-- this index were non-HOT before it existed and remain exactly as non-HOT.
--
-- THE COST OF PARTIAL is the same one jorb_tags_idx documents: a query may
-- use this index only when its own clauses syntactically IMPLY the predicate,
-- so the concurrency check must spell out the same state list. It does
-- (pyjobby/scheduler.py, ScheduleSafetyManager.check_concurrency), and
-- tests/test_scale_plans.py fails if that stops being true.
CREATE INDEX jorb_schedule_id_idx ON jorb (schedule_id)
    WHERE schedule_id IS NOT NULL
      AND state IN ('queued', 'claimed', 'running', 'waiting');
-- idempotent enqueue
CREATE UNIQUE INDEX jorb_deadline_idx ON jorb (deadline_key, queue)
    WHERE state = 'queued' AND deadline_key IS NOT NULL;

-- ----------------------------------------------------------------------------
-- Autovacuum, tuned for this table's write pattern rather than left at the
-- server defaults. A job costs ~4 row versions (insert, claim, run, terminal),
-- so a busy install produces dead tuples in the millions per hour. The default
-- scale factor of 0.2 means "wait until 20% of the table is garbage", which on
-- a large jorb is both far too late and then far too much work at once; the
-- claim index bloats in the meantime.
--
-- fillfactor leaves room on each page for an updated row version to live
-- beside its original, which is what allows a HOT update -- an update that
-- does not have to touch every index. That is why `updated` is not indexed.
ALTER TABLE jorb SET (
    autovacuum_vacuum_scale_factor  = 0.02,
    autovacuum_vacuum_threshold     = 1000,
    autovacuum_analyze_scale_factor = 0.02,
    autovacuum_vacuum_cost_limit    = 2000,
    fillfactor                      = 85
);

