-- ============================================================================
-- Core job table
-- ============================================================================
CREATE TABLE jorb (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue           TEXT        NOT NULL DEFAULT 'default',
    capability      TEXT,                 -- worker must advertise this to claim
    prio            INTEGER     NOT NULL DEFAULT 100,  -- lower = more urgent
    state           jorbstate   NOT NULL DEFAULT 'queued',
    job_class       TEXT        NOT NULL,
    kwargs          JSONB       NOT NULL DEFAULT '{}',
    admin_data      JSONB       NOT NULL DEFAULT '{}',
    result          JSONB,
    uid             BIGINT,               -- multi-tenancy tag
    tags            JSONB       NOT NULL DEFAULT '{}',  -- caller's own labels

    -- dependency edges
    run_group       BIGINT,
    waitfor_group   BIGINT,
    waitfor_job     BIGINT,
    dag_id          BIGINT,

    -- idempotent enqueue: one queued row per (deadline_key, queue)
    deadline_key    TEXT,

    -- at-most-once identity: one row per identity_key IN ANY STATE, for as
    -- long as the row exists (see the COMMENT -- retention is the bound)
    identity_key    TEXT,

    -- quiet-period collapse: one QUEUED row per debounce_key, whose
    -- run_after every duplicate enqueue pushes further out (see the COMMENT)
    debounce_key    TEXT,
    -- the ceiling that collapse may never push run_after past, NULL when the
    -- caller asked for no cap (see the COMMENT)
    debounce_deadline TIMESTAMPTZ,

    -- fair-share lane: whose work this is, enforced only on queues with
    -- jorb_queue.partition_limits set (see the COMMENT)
    partition_key   TEXT,

    -- provenance: the recurring schedule that fired this job into existence
    schedule_id     BIGINT,

    -- lineage: the job this one was FORKED from (see the COMMENT)
    forked_from     BIGINT REFERENCES jorb (id) ON DELETE SET NULL,

    -- execution bookkeeping
    run_count       INTEGER     NOT NULL DEFAULT 0,
    error_count     INTEGER     NOT NULL DEFAULT 0,
    error_message   TEXT,
    error_backtrace TEXT,
    run_epoch       INTEGER     NOT NULL DEFAULT 0,  -- fencing token (see COMMENT)
    cancel_requested BOOLEAN    NOT NULL DEFAULT FALSE,
    -- demand latch for the jorb_done / jorb_event channels (see the
    -- notification section at the bottom of this file)
    awaited         BOOLEAN     NOT NULL DEFAULT FALSE,

    -- who has it
    claimed_by      BIGINT,               -- jorb_worker.id
    worker_pid      INTEGER,
    worker_host     TEXT,

    -- timing (all timestamptz)
    created         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated         TIMESTAMPTZ NOT NULL DEFAULT now(),
    run_after       TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at      TIMESTAMPTZ,
    started         TIMESTAMPTZ,
    finished        TIMESTAMPTZ,
    timeout_at      TIMESTAMPTZ
);

COMMENT ON TABLE jorb IS 'Jobs. One row per job for its whole life; retries re-queue the same row.';
COMMENT ON COLUMN jorb.prio IS 'Lower numbers are more urgent; workers claim jobs with prio <= their ceiling.';
COMMENT ON COLUMN jorb.claimed_at IS 'When this attempt was admitted by a worker. Rate limits count admissions, not execution starts: started is written after the claim commits, so counting it lets a claim miss the claim before it.';
COMMENT ON COLUMN jorb.run_epoch IS 'Fencing token, NOT an attempt counter (that is run_count). Advances whenever the job enters an attempt (claim) or leaves one (finish, crash, cancel, retry, requeue, reschedule), so an execution the row has moved past may not write results, checkpoints, events, or mailbox messages.';
COMMENT ON COLUMN jorb.awaited IS 'Someone has waited on this job (wait_for_result/get_event). Set by the waiter BEFORE it looks at the state, and never cleared: it is the demand signal that switches the jorb_done and jorb_event notifications on for this job, and it costs one HOT update per job that is ever awaited.';
COMMENT ON COLUMN jorb.tags IS 'The CALLER''s labels (customer, region, batch), flat key -> scalar, for filtering jobs by something the application means. Deliberately NOT admin_data: that column is the platform''s own execution config (max_retries, timeout_seconds, save_result, schedule metadata), which nobody filters on, so indexing it would tax every enqueue to make no query faster. The one thing anybody DID filter admin_data by is now jorb.schedule_id: a fact worth querying by is worth a column, because the alternative is an expression index over a jsonb blob written by every job to answer a question asked about a handful of them.';
COMMENT ON COLUMN jorb.waitfor_group IS 'Becomes queued only when ALL jobs with run_group = this value are finished.';
COMMENT ON COLUMN jorb.waitfor_job IS 'Becomes queued only when the job with this id is finished.';
COMMENT ON COLUMN jorb.forked_from IS 'The job this one was forked from: a fork is a NEW row that re-executes an existing job''s work from step N, with steps 1..N-1 copied in as checkpoints (jorb.admin_data->''fork'' records which N, and how many rows were copied). Retry and re-run keep ONE row; a fork does not, which is the whole point -- the source is never touched, so a fork of a running job is safe and a fork of a finished one does not disturb its result. ON DELETE SET NULL because LINEAGE IS BEST-EFFORT AUDIT, NOT A DEPENDENCY: retention reaps terminal jobs on its own schedule and the source is usually older than the fork, so a fork must outlive the row it came from rather than be deleted with it (ON DELETE CASCADE) or pin it forever (RESTRICT). A NULL here therefore means "no source, or the source has aged out", and the fork''s own history row -- written at insert, before anything could be reaped -- keeps the source id and step regardless.';
COMMENT ON COLUMN jorb.identity_key IS 'The CALLER''s name for a piece of work, unique across this table IN ANY STATE: enqueueing an identity that already exists returns the existing job instead of writing a second row. THE CONTRAST WITH deadline_key IS THE WHOLE POINT, and the two indexes say it: jorb_deadline_idx is unique only among QUEUED rows and per QUEUE, so a deadline_key collapses duplicate submissions of work that has not started and then RE-ARMS the moment the job is claimed -- tomorrow''s "send the 09:00 digest" is a legitimate second job. jorb_identity_idx has no state predicate and no queue column, so an identity_key is claimed by the row for its entire life, running and finished and crashed alike, and never re-arms. RETENTION IS THE HORIZON, and it is the honest bound on "at most once": when the sweep reaps the terminal row (--retention-days) the key goes with it and the same identity enqueued afterwards creates a new job. A caller who needs uniqueness beyond the horizon scopes the key to a time it can name -- an order id, a date stamp, a ULID -- rather than expecting the platform to remember further back than it remembers anything else. NOT inherited by a fork (FORK_JOB_SQL lists its columns and this is not one: two live rows sharing an identity would make it mean nothing), and untouched by retry, rerun and dlq retry, which requeue the SAME row and so keep the identity they already had.';
COMMENT ON COLUMN jorb.debounce_key IS 'The CALLER''s name for a BURST of equivalent enqueues that should become ONE job, run once the burst stops. Every duplicate enqueue of the key updates the one queued row rather than writing another: run_after moves to now + the caller''s quiet period and kwargs are REPLACED, so the collapsed job runs with the freshest arguments and last writer wins. THE DISTINCTION FROM THE OTHER TWO KEYS IS WHAT A DUPLICATE DOES, not what the index covers: a deadline_key IGNORES duplicates (the second enqueue raises and nothing about the first job changes), an identity_key RETURNS the existing job untouched, and a debounce_key MOVES the job -- later, and with different arguments. So debounce is only for work whose latest arguments are the right ones; work that must run with the arguments it was first submitted with wants deadline_key. THE KEY IS HELD WHILE THE ROW IS QUEUED AND HAS NEVER BEEN CLAIMED, which jorb_debounce_idx says and which means it is released at the CLAIM and never taken back: once a worker takes the collapsed job, the next enqueue of the key opens a NEW collapse window, and the two rows coexist (one running, one parked) with no conflict -- as do a RETRY of the first and a parked second, since a requeued row no longer holds the key it came in with. A duplicate arriving after run_after has passed but BEFORE a worker claims the row still collapses onto it and pushes the wait out again -- the work has not started, so there is nothing to collapse it out of. NOT inherited by a fork (FORK_JOB_SQL lists its columns and this is not one). Set only by JobClient.debounce(), which owns the bounce-or-insert statement pair; combining it with identity_key or deadline_key in one enqueue is refused, because their promises about a duplicate contradict each other.';
COMMENT ON COLUMN jorb.debounce_deadline IS 'The ceiling a bounce may not push run_after past, written by the FIRST enqueue of a debounce_key as now + the caller''s cap and never rewritten. It exists because collapse without a bound is starvation: a key bounced faster than its own quiet period is deferred forever, and the job that was supposed to run "once the burst stops" never runs at all. Persisted rather than recomputed per call so that bounces from OTHER processes -- which know only their own cap, or none -- still respect the ceiling the first caller set. NULL means the caller accepted unbounded deferral, which is a legitimate choice for work that is worthless until the burst really does stop. Bounces clamp with LEAST, so once the deadline is reached run_after stops moving and the job becomes claimable while duplicates keep collapsing onto it.';
COMMENT ON COLUMN jorb.partition_key IS 'The FAIR-SHARE LANE this job belongs to -- the caller''s name for whose work it is (a tenant, a customer, an api key). Inert by itself: it is a label like uid or tags until the job''s queue sets jorb_queue.partition_limits, and on every other queue the claim path never reads it. On a queue that DOES set it, the queue''s max_concurrency and rate_limit are counted per DISTINCT VALUE of this column instead of per queue, so one lane saturating its own share cannot starve the rest. THE NULL LANE IS A LANE, and this is the rule the design exists to protect: jobs that carry no partition_key form ONE lane among the others, capped and admitted exactly like a named one. They are never hidden from the claim and never refused for being unlabelled -- a scheme that silently blackholes the work nobody remembered to label is a worse failure than the starvation it was meant to fix. INHERITED BY A FORK, unlike the three dedupe keys: this describes whose work it is, not which piece of work it is, so a fork of a tenant''s job is still that tenant''s job (the same reasoning that carries uid and tags across). Kept through retry, rerun and dlq retry, which requeue the same row. Bounded at enqueue (client.MAX_PARTITION_KEY_LENGTH) because it is a grouping key read inside the serialised claim section, not a payload.';
COMMENT ON COLUMN jorb.schedule_id IS 'The jorb_schedule row that fired this job, NULL for every job enqueued directly. This is the SOLE source of that fact -- it used to live in admin_data->>''schedule_id'', which no index could serve, so the scheduler''s max_concurrent_jobs check scanned the whole job table on every firing. Deliberately NOT a foreign key: jobs outlive the schedules that made them (deleting a schedule must not delete or rewrite its history), and a REFERENCES here would need an index over EVERY schedule-created job to serve the cascade, undoing the point of the partial index below.';

-- the poll/claim path
CREATE INDEX jorb_claim_idx ON jorb (queue, prio, run_after)
    WHERE state = 'queued';
-- rate limiting counts recent admissions per queue
CREATE INDEX jorb_claimed_at_idx ON jorb (queue, claimed_at)
    WHERE claimed_at IS NOT NULL;
-- duration/throughput reporting
CREATE INDEX jorb_started_idx ON jorb (queue, started)
    WHERE started IS NOT NULL;
-- reaper scans
CREATE INDEX jorb_inflight_idx ON jorb (state, updated)
    WHERE state IN ('claimed', 'running');
-- the per-lane concurrency count on a partitioned queue (see claim_jorb).
-- It runs INSIDE the per-queue advisory lock, which is the most expensive
-- place in the system for a query to be slow, and it needs a column
-- jorb_inflight_idx does not carry -- so without this it would read every
-- in-flight row in the FLEET and heap-fetch each one to find out whose queue
-- and whose lane it is. Here the whole group-by is an index-only scan over
-- one queue's in-flight rows.
--
-- THE CHEAPEST INDEX IN THE SCHEMA TO KEEP, and the predicate is why: it
-- holds only claimed/running rows, so it is bounded by work in flight (the
-- fleet's size) rather than by the table, and enqueue -- the hot write --
-- never touches it at all, because a queued row is not in it. The two
-- transitions that are, claim and finish, already write jorb_inflight_idx
-- and jorb_claim_idx and are already non-HOT for having `state` as a
-- predicate column, so this adds one index entry to each and no new class of
-- work. Not partial on `partition_key IS NOT NULL`: the NULL lane is a lane
-- (see the COMMENT on jorb.partition_key) and its count has to come from the
-- same scan as everyone else's.
CREATE INDEX jorb_partition_inflight_idx ON jorb (queue, partition_key)
    WHERE state IN ('claimed', 'running');
-- retention: the sweep asks "which terminal jobs aged out?" every cycle, and
-- once it has caught up the honest answer is usually "none". Without this it
-- reads the whole terminal backlog to say so -- measured at 300k rows that is
-- already a full scan, and a busy install keeps orders of magnitude more.
-- Indexed on the expression the sweep actually filters by.
CREATE INDEX jorb_retention_idx ON jorb (COALESCE(finished, updated))
    WHERE state IN ('finished', 'crashed', 'cancelled');
-- checkpoint retention is a SEPARATE, shorter window and a NARROWER state
-- set: only 'finished' jobs have their checkpoints reaped early, because
-- 'crashed'/'cancelled' are retryable and a retry resumes from checkpoints.
-- A dedicated partial index keeps that sweep from walking past (and
-- discarding) the crashed/cancelled terminal rows the all-terminal index
-- above would hand it -- on a crash-heavy install that discard is otherwise
-- proportional to the terminal backlog.
CREATE INDEX jorb_finished_retention_idx ON jorb (COALESCE(finished, updated))
    WHERE state = 'finished';
-- reporting windows. Deliberately on `created` and NOT on `updated`:
-- `updated` is rewritten by every state change, so indexing it would add an
-- index write to each of the ~4 updates per job AND block HOT updates on the
-- hottest table in the system -- paying in permanent bloat for a read that
-- happens on a scrape interval. `created` is written once.
CREATE INDEX jorb_created_idx ON jorb (created);
CREATE INDEX jorb_timeout_idx ON jorb (timeout_at)
    WHERE state = 'running' AND timeout_at IS NOT NULL;
-- dependency wakeups
CREATE INDEX jorb_waitfor_job_idx   ON jorb (waitfor_job)   WHERE state = 'waiting';
CREATE INDEX jorb_waitfor_group_idx ON jorb (waitfor_group) WHERE state = 'waiting';
-- Partial like their neighbours, and for the same reason: run_group and uid
-- are NULL on the overwhelming majority of jobs (only grouped work and
-- multi-tenant callers set them), but a plain btree indexes NULLs too. That
-- means an index entry written on every insert and maintained by every
-- vacuum, for rows the index can never usefully answer a question about --
-- pure write amplification on the hottest table in the system.
CREATE INDEX jorb_run_group_idx ON jorb (run_group) WHERE run_group IS NOT NULL;
-- The group-wake gate ("is any member still unfinished?") runs on the
-- completion path of EVERY grouped job. Its NOT EXISTS probe wants one
-- unfinished witness; over jorb_run_group_idx it walks past finished members
-- to find one, an O(members) tail exactly when the group nears completion.
-- This index holds only the unfinished members, so the probe is O(1) at any
-- group size -- and it SHRINKS to empty as groups finish, so its steady-state
-- write cost is bounded by grouped work in flight, not by group history.
CREATE INDEX jorb_group_unfinished_idx ON jorb (run_group)
    WHERE run_group IS NOT NULL AND state != 'finished';
CREATE INDEX jorb_uid_idx       ON jorb (uid)       WHERE uid IS NOT NULL;
-- Fork lineage, partial for the same reason as the two above: almost no job
-- is a fork, so the predicate keeps every ordinary enqueue out of the index.
--
-- The reader that MAKES this index mandatory is not a query anybody writes.
-- `forked_from REFERENCES jorb ON DELETE SET NULL` means PostgreSQL runs
-- `UPDATE jorb SET forked_from = NULL WHERE forked_from = <id>` for EVERY row
-- deleted from this table -- and retention deletes in batches of thousands,
-- forever. Unindexed that is a sequential scan of the largest table in the
-- system per reaped job, i.e. the retention sweep silently becoming O(rows
-- deleted x table size). The referential-integrity query is `forked_from =
-- $1`, a strict clause, which implies `forked_from IS NOT NULL` and so may
-- use this partial index (THE COST OF PARTIAL, spelled out on jorb_tags_idx
-- below, is a real cost here and it is paid: tests/test_scale_plans.py
-- asserts the delete path is an index scan at scale, not a seq scan).
--
-- It also answers the lineage question in the other direction -- "what was
-- forked from this job?", which `pj-admin jobs inspect` asks about the source.
CREATE INDEX jorb_forked_from_idx ON jorb (forked_from) WHERE forked_from IS NOT NULL;
CREATE INDEX jorb_dag_idx           ON jorb (dag_id) WHERE dag_id IS NOT NULL;
-- Caller-supplied labels, and partial for exactly the reason the three above
-- are: almost every job sets no tags at all, and a plain GIN index would
-- still store an entry for each of them -- an object with no keys yields no
-- keys to index, so GIN records it as an empty item purely so that a full
-- index scan can find the row again. That is write amplification on the
-- hottest table in the system in exchange for nothing.
--
-- The predicate keeps the untagged enqueue path -- the hot one -- out of the
-- index entirely, and that is measured, not assumed. At 16 concurrent
-- connections with one transaction per job, untagged enqueue is unchanged by
-- this index existing (28.7k vs 28.9k jobs/s, medians of nine interleaved
-- pj-bench pairs, which is noise on a shared box). Enqueue WITH tags
-- populated measures 0.93-1.04x of untagged even when every job carries a
-- DISTINCT tag value, GIN's pessimal case: fastupdate parks new entries in
-- the pending list and the merge is autovacuum's problem, not the enqueuing
-- transaction's. tests/test_job_tags.py holds both measurements, and asserts
-- the index does not grow at all when 10,000 untagged jobs are inserted.
--
-- THE COST OF PARTIAL, which every caller has to pay attention to: a query
-- may use a partial index only when its own clauses IMPLY the predicate, and
-- PostgreSQL proves that syntactically. It cannot derive `tags <> '{}'` from
-- `tags @> '{"customer":"acme"}'`, so a filter that omits the predicate is
-- correct and sequentially scans the table. Every tag filter in this codebase
-- is therefore built by client.tags_filter_sql, which emits both clauses.
CREATE INDEX jorb_tags_idx ON jorb USING GIN (tags) WHERE tags <> '{}';
-- The scheduler's max_concurrent_jobs check: "how many of MY jobs are still
-- in flight?", asked once per firing of every schedule. Partial on BOTH
-- clauses, and each one is doing separate work.
--
--   schedule_id IS NOT NULL keeps the overwhelming majority of jobs -- every
--   one a client enqueued -- out of the index entirely, so the hot enqueue
--   path evaluates a null check and writes nothing. Same trade as
--   jorb_run_group_idx, jorb_uid_idx and jorb_tags_idx above, and measured
--   the same way: 27,941 vs 28,010 jobs/s across nine INTERLEAVED
--   `pj-bench enqueue --concurrency 16 --repeat 3` pairs, which is no
--   difference at all against a within-run spread of 10-33%
--   (docs/RECURRING_SCHEDULER.md#performance carries the numbers, and
--   tests/test_scale_plans.py asserts the index does not grow by one page
--   when 20,000 client-enqueued jobs are inserted).
--
--   state IN (...) is what stops this becoming the very problem it fixes. A
--   schedule accumulates jobs forever -- a minutely one writes ~525k a year --
--   so an index on schedule_id alone would hand the check every job the
--   schedule has EVER created and make it discard the terminal ones. That
--   costs a scan and passes a no-seq-scan check, which is exactly the failure
--   tests/utils/plans.rows_removed_by_filter exists to catch. Restricted to
--   the live states the index holds only in-flight work, which the limit
--   itself bounds: the check's cost tracks the schedule's own concurrency and
--   not the age of the install.
--
-- state is already a predicate column of jorb_claim_idx, jorb_inflight_idx
-- and jorb_retention_idx, so the transitions that move a row in and out of
-- this index were non-HOT before it existed and remain exactly as non-HOT.
--
-- THE COST OF PARTIAL is the same one jorb_tags_idx documents: a query may
-- use this index only when its own clauses syntactically IMPLY the predicate,
-- so the concurrency check must spell out the same state list. It does
-- (pyjobby/scheduler.py, ScheduleSafetyManager.check_concurrency), and
-- tests/test_scale_plans.py fails if that stops being true.
CREATE INDEX jorb_schedule_id_idx ON jorb (schedule_id)
    WHERE schedule_id IS NOT NULL
      AND state IN ('queued', 'claimed', 'running', 'waiting');
-- idempotent enqueue
CREATE UNIQUE INDEX jorb_deadline_idx ON jorb (deadline_key, queue)
    WHERE state = 'queued' AND deadline_key IS NOT NULL;
-- at-most-once identity. Read this one directly against the line above: the
-- two differ in exactly the places that decide what each key PROMISES.
--
--   No `state = 'queued'`. The deadline index holds only queued rows, so a
--   deadline_key is released the instant a worker claims the job and the
--   next enqueue of it is a new job -- collapse-then-re-arm, which is what
--   "one pending digest at a time" wants. This index holds EVERY row with a
--   key, so the identity is held by running, finished and crashed jobs too
--   and no second row can ever exist while the first one does.
--
--   No `queue`. A deadline_key is scoped per queue because it is about the
--   pending work in that queue; an identity names the WORK, and the same
--   work routed to another queue is still the same work.
--
-- Partial for the reason every partial index here is: identity_key is NULL
-- on the overwhelming majority of jobs, and an unconditional unique index
-- would write an entry for each of them -- write amplification on the
-- hottest table in the system, on the enqueue path, for rows it could never
-- answer a question about. Unique partial indexes are also what ON CONFLICT
-- infers against, and inference requires the predicate to be RESTATED in the
-- statement (`ON CONFLICT (identity_key) WHERE identity_key IS NOT NULL`);
-- pyjobby/client.py ENQUEUE_IDENTIFIED_SQL is the one place that does.
--
-- THE LIFETIME OF AN ENTRY IS THE LIFETIME OF THE ROW, so retention bounds
-- the guarantee (see the COMMENT on the column). Nothing else frees a key:
-- retry, rerun and dlq retry all requeue the same row.
CREATE UNIQUE INDEX jorb_identity_idx ON jorb (identity_key)
    WHERE identity_key IS NOT NULL;
-- quiet-period collapse. Read this one against the two above as well: all
-- three are partial unique indexes over a caller-chosen key, and the shape
-- of each is the promise it makes.
--
--   `state = 'queued' AND run_count = 0` -- "queued, and never claimed",
--   which is exactly "the collapse window is still open". Not
--   `run_after > now()`, although "parked" is what a debounced row usually
--   is: an index predicate must be IMMUTABLE, so the clock cannot appear in
--   one -- and it should not, since the question is "has this work
--   started?", and between run_after passing and a worker claiming the row
--   it has not.
--
--   RUN_COUNT IS WHAT MAKES THE RELEASE PERMANENT, and it is not
--   decoration. claim_jorb increments run_count, so it is 0 on exactly
--   those rows no worker has ever admitted. Without it, a row that was
--   claimed, failed and was RETRIED would come back to 'queued' still
--   holding the key -- and if a burst had opened a new window in the
--   meantime, that retry UPDATE (pyjobby/pj.py STMTS["retry"], and every
--   other requeue path: the monitor's dead-worker sweep, `jobs retry`)
--   would violate this index inside a worker's failure handler, leaving a
--   job that can never be retried. With it, the key is released at the
--   FIRST claim and can never be taken back, which is what "released at the
--   claim" has to mean for a row that lives on. The row keeps the key as
--   provenance -- `jobs inspect` still names the window a finished job came
--   out of -- and holds nothing.
--
--   No `queue` column, unlike jorb_deadline_idx. A debounce_key names a
--   burst of events in the application ("cart 991 changed"), and the same
--   burst routed to another queue is still one burst.
--
-- WHAT MAKES IT DIFFERENT FROM ITS TWO NEIGHBOURS IS NOT THE PREDICATE, it
-- is what a duplicate enqueue DOES: deadline_key raises and leaves the job
-- alone, identity_key hands back the job untouched, and a debounce_key
-- UPDATES the job -- pushing run_after out and replacing kwargs. The column
-- COMMENT spells that out; the index only guarantees there is one row to
-- update.
--
-- Partial for the reason every partial index here is: debounce_key is NULL
-- on the overwhelming majority of jobs. And as with jorb_identity_idx, ON
-- CONFLICT inference requires the predicate RESTATED in the statement;
-- pyjobby/client.py ENQUEUE_DEBOUNCED_SQL is the one place that does, and
-- DEBOUNCE_BOUNCE_SQL restates it again for a different reason (its own
-- EvalPlanQual recheck).
CREATE UNIQUE INDEX jorb_debounce_idx ON jorb (debounce_key)
    WHERE debounce_key IS NOT NULL AND state = 'queued' AND run_count = 0;

-- ----------------------------------------------------------------------------
-- Autovacuum, tuned for this table's write pattern rather than left at the
-- server defaults. A job costs ~4 row versions (insert, claim, run, terminal),
-- so a busy install produces dead tuples in the millions per hour. The default
-- scale factor of 0.2 means "wait until 20% of the table is garbage", which on
-- a large jorb is both far too late and then far too much work at once; the
-- claim index bloats in the meantime.
--
-- fillfactor leaves room on each page for an updated row version to live
-- beside its original, which is what allows a HOT update -- an update that
-- does not have to touch every index. That is why `updated` is not indexed.
ALTER TABLE jorb SET (
    autovacuum_vacuum_scale_factor  = 0.02,
    autovacuum_vacuum_threshold     = 1000,
    autovacuum_analyze_scale_factor = 0.02,
    autovacuum_vacuum_cost_limit    = 2000,
    fillfactor                      = 85
);

