-- ============================================================================
-- DXE: step checkpoints (durable execution)
-- ============================================================================
CREATE TABLE jorb_step (
    job_id    BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    step_seq  INTEGER     NOT NULL,
    name      TEXT        NOT NULL,
    output    JSONB,
    error     TEXT,                    -- recorded exception; replay re-raises
    run_epoch INTEGER     NOT NULL,    -- which attempt produced this checkpoint
    started   TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished  TIMESTAMPTZ,
    PRIMARY KEY (job_id, step_seq)
);

COMMENT ON TABLE jorb_step IS 'DXE checkpoints: a completed step is never re-executed on retry/resume; a name mismatch at a step_seq means nondeterministic job code.';

-- ============================================================================
-- DXE: key/value events (job publishes, anyone reads/awaits)
-- ============================================================================
CREATE TABLE jorb_event (
    job_id  BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    key     TEXT        NOT NULL,
    value   JSONB       NOT NULL,
    updated TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (job_id, key)
);

-- ============================================================================
-- DXE: durable job-to-job messages
-- ============================================================================
CREATE TABLE jorb_mailbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dest_job_id BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    topic       TEXT,
    message     JSONB       NOT NULL,
    created     TIMESTAMPTZ NOT NULL DEFAULT now(),
    consumed_at TIMESTAMPTZ
);

CREATE INDEX jorb_mailbox_pending_idx ON jorb_mailbox (dest_job_id, topic, id)
    WHERE consumed_at IS NULL;

-- Retention drives off consumed messages, every cycle, forever. A long-lived
-- job reads mail for months, so the job-scoped cascade never reaches them and
-- this is the only thing that does -- unindexed it would scan the whole
-- mailbox each pass and get slower forever.
CREATE INDEX jorb_mailbox_consumed_idx ON jorb_mailbox (consumed_at)
    WHERE consumed_at IS NOT NULL;

