-- ============================================================================
-- Transition history (first-class audit; retries keep one job id)
-- ============================================================================
CREATE TABLE jorb_history (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- cascades like every other child of jorb: history is the biggest of
    -- them, so without the key retention would free the small tables and
    -- leave the largest one growing forever
    job_id  BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- enqueued|queued|claimed|running|waiting|finished|crashed|cancelled --
    -- 'enqueued' on INSERT, otherwise NEW.state::text, so the domain is
    -- 'enqueued' plus the jorbstate labels and nothing else. See the COMMENT
    -- below, which is checked against jorbstate by a test.
    event   TEXT        NOT NULL,
    detail  JSONB       NOT NULL DEFAULT '{}'
);

CREATE INDEX jorb_history_job_idx ON jorb_history (job_id, id);
-- retention: live-job history is reachable ONLY by age — the cascade fires
-- at job deletion, which a job that never terminates (a parked durable
-- machine, ~3 rows per wake, forever) never reaches. The sweep walks this
-- in age order and stops at its batch.
CREATE INDEX jorb_history_at_idx ON jorb_history (at);

-- Append-only until retention deletes in bulk, so it needs a low scale factor
-- to clean up promptly after a sweep, but no fillfactor headroom.
ALTER TABLE jorb_history SET (
    autovacuum_vacuum_scale_factor = 0.05,
    autovacuum_vacuum_threshold    = 5000,
    autovacuum_vacuum_cost_limit   = 2000
);


COMMENT ON TABLE jorb_history IS 'Every state transition with worker/epoch/error detail; the per-attempt audit trail (jobs keep one row in jorb for life).';
COMMENT ON COLUMN jorb_history.event IS 'Domain: enqueued, queued, claimed, running, waiting, finished, crashed, cancelled. That list is exhaustive and machine-checked (tests/test_history_event_domain.py) because record_jorb_history() writes ''enqueued'' on INSERT and NEW.state::text on every other row -- so the domain is ''enqueued'' plus the jorbstate labels, and it changes only when jorbstate does. There is no verb vocabulary here and never was: a retry is a queued row whose detail.from is running, a timeout is a queued or crashed row with detail.error set, and dead-worker recovery is a queued row written by the monitor. Counting ATTEMPTS therefore means counting running rows, which is what pj-admin stats does. The column is TEXT rather than jorbstate purely so enqueued can coexist with the states.';

