-- ============================================================================
-- Recurring schedules (cron) + execution log
-- ============================================================================
CREATE TABLE jorb_schedule (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      TEXT    NOT NULL UNIQUE,
    description               TEXT,
    job_class                 TEXT    NOT NULL,
    kwargs                    JSONB   NOT NULL DEFAULT '{}',
    queue                     TEXT    NOT NULL DEFAULT 'default',
    prio                      INTEGER NOT NULL DEFAULT 100,
    capability                TEXT,
    cron_expr                 TEXT    NOT NULL,
    timezone                  TEXT    NOT NULL DEFAULT 'UTC',
    enabled                   BOOLEAN NOT NULL DEFAULT TRUE,
    max_concurrent_jobs       INTEGER NOT NULL DEFAULT 1,
    jitter_seconds            INTEGER NOT NULL DEFAULT 0,
    -- How many MISSED ticks a recovering scheduler may catch up on. The
    -- single integer is both the opt-in and the bound, deliberately: 0 (the
    -- default) never backfills -- a scheduler that was down skips the ticks
    -- it missed and next_run advances from now -- and N > 0 enqueues at most
    -- the N most recent missed ticks, never the older ones. Unbounded
    -- backfill is how a recovered scheduler floods an already-behind queue
    -- with an outage's worth of work, so there is no way to ask for it.
    backfill_limit            INTEGER NOT NULL DEFAULT 0,
    backpressure_threshold    INTEGER          DEFAULT 1000,
    circuit_breaker_threshold INTEGER NOT NULL DEFAULT 5,
    consecutive_failures      INTEGER NOT NULL DEFAULT 0,
    next_run                  TIMESTAMPTZ NOT NULL,
    last_run                  TIMESTAMPTZ,
    last_success              TIMESTAMPTZ,
    last_failure              TIMESTAMPTZ,
    run_count                 BIGINT  NOT NULL DEFAULT 0,
    success_count             BIGINT  NOT NULL DEFAULT 0,
    failure_count             BIGINT  NOT NULL DEFAULT 0,
    skip_count                BIGINT  NOT NULL DEFAULT 0,
    created                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by                TEXT
);

CREATE INDEX jorb_schedule_due_idx ON jorb_schedule (next_run) WHERE enabled;

CREATE TABLE jorb_schedule_log (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id            BIGINT NOT NULL REFERENCES jorb_schedule (id) ON DELETE CASCADE,
    schedule_name          TEXT   NOT NULL,
    scheduled_time         TIMESTAMPTZ NOT NULL,
    actual_time            TIMESTAMPTZ NOT NULL DEFAULT now(),
    result                 TEXT   NOT NULL,  -- success|failure|skipped
    skip_reason            TEXT,
    job_id                 BIGINT,
    error_message          TEXT,
    duration_ms            INTEGER,
    queue_depth_at_run     INTEGER,
    concurrent_jobs_at_run INTEGER,
    jitter_applied_seconds INTEGER
);

-- One row per schedule EXECUTION, per schedule, forever: this index serves
-- `pj-admin schedule history NAME` and the "keep the newest execution"
-- refusal in the retention sweep, both of which are "the last N rows of one
-- schedule" -- id ascends with actual_time, so a backward scan answers both.
CREATE INDEX jorb_schedule_log_idx ON jorb_schedule_log (schedule_id, id);

-- Retention. jorb_schedule_log cascades from jorb_schedule, which operators
-- essentially never delete, so before the sweep this was the one table in the
-- system with no upper bound at all: a minutely schedule writes ~43k rows a
-- month and keeps them until the schedule itself is dropped. The sweep filters
-- on actual_time, so it is indexed on actual_time -- ordering by id instead
-- would make the planner walk the primary key and filter every row to
-- discover that nothing has expired, which is the exact pathology
-- jorb_retention_idx exists to prevent on jorb.
CREATE INDEX jorb_schedule_log_retention_idx ON jorb_schedule_log (actual_time);

