-- ============================================================================
-- DAG orchestration
-- ============================================================================
CREATE TABLE jorb_dag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT,
    created     TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed   TIMESTAMPTZ,
    metadata    JSONB NOT NULL DEFAULT '{}'
);

-- Retention, and it is a CORRECTNESS index, not just a storage one. A DAG is
-- the PARENT here (jorb.dag_id is the child side, ON DELETE SET NULL), so
-- deleting jobs never touches this table: without a sweep a DAG row outlives
-- every job it describes, and jorb_dag_status -- a LEFT JOIN -- then reports
-- it as total_jobs = 0 forever. That is a wrong answer, not a stale one, and
-- it is what `pj-admin dag list` shows an operator. The sweep reaps DAGs that
-- have outlived the retention window AND have no jobs left; it filters and
-- orders on created, so that is what is indexed.
--
-- created, not completed: a DAG whose jobs all crashed never completes at
-- all, and created is the only clock every DAG has. It is also always
-- EARLIER than any of its jobs' terminal times (the jobs are created inside
-- the same transaction, after this row), so a DAG becomes eligible in the
-- same cycle that retention removes its last job -- the empty-DAG window is
-- one monitor cycle wide instead of unbounded.
CREATE INDEX jorb_dag_retention_idx ON jorb_dag (created);

COMMENT ON TABLE jorb_dag IS 'One row per DAG execution, holding only what is not on the jobs themselves (name, metadata, completion). Its jobs point AT it (jorb.dag_id, ON DELETE SET NULL), so its lifetime is bounded by the monitor''s DAG sweep and not by any cascade: see jorb_dag_retention_idx.';

CREATE TABLE jorb_dependencies (
    job_id     BIGINT NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    depends_on BIGINT NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    PRIMARY KEY (job_id, depends_on)
);

-- The primary key leads with job_id, so THAT cascade is indexed; depends_on
-- is a second foreign key to the same table and Postgres indexes neither
-- automatically. Without this, deleting a job sequentially scans this table
-- looking for edges that point at it -- once per deleted job, which is
-- exactly what retention does in bulk.
CREATE INDEX jorb_dependencies_depends_on_idx ON jorb_dependencies (depends_on);

-- SET NULL and not CASCADE, deliberately: dropping a DAG row must never
-- delete jobs. The direction that matters for retention is the other one --
-- deleting a job leaves this parent behind, which is why jorb_dag needs a
-- sweep of its own (see jorb_dag_retention_idx).
ALTER TABLE jorb ADD CONSTRAINT jorb_dag_fk
    FOREIGN KEY (dag_id) REFERENCES jorb_dag (id) ON DELETE SET NULL;

-- LEFT JOIN, and it stays a LEFT JOIN: a DAG with no jobs is a real state
-- during construction, and an inner join would hide a DAG from `dag list`
-- exactly while its jobs are being created. The failure mode this shape has
-- -- a DAG whose jobs retention removed reporting total_jobs = 0 forever --
-- is fixed by REMOVING the row (sweep_orphaned_dags), not by hiding it: a
-- view cannot tell "never had jobs" from "had jobs, they aged out", so any
-- answer it invents for one is wrong for the other.
CREATE VIEW jorb_dag_status AS
    SELECT d.id AS dag_id,
           d.name,
           d.created,
           d.completed,
           count(j.id)                                            AS total_jobs,
           count(j.id) FILTER (WHERE j.state = 'finished')        AS finished_jobs,
           count(j.id) FILTER (WHERE j.state = 'crashed')         AS crashed_jobs,
           count(j.id) FILTER (WHERE j.state = 'cancelled')       AS cancelled_jobs,
           count(j.id) FILTER (WHERE j.state IN ('queued','claimed','running','waiting')) AS pending_jobs
    FROM jorb_dag d
    LEFT JOIN jorb j ON j.dag_id = d.id
    GROUP BY d.id;

CREATE VIEW jorb_dag_timeline AS
    SELECT j.dag_id,
           j.id AS job_id,
           j.job_class,
           j.state,
           j.started,
           j.finished,
           EXTRACT(EPOCH FROM (j.finished - j.started)) AS duration_seconds
    FROM jorb j
    WHERE j.dag_id IS NOT NULL;

