-- ============================================================================
-- pyjobby unified schema v1
-- ============================================================================
-- Forward-only canonical schema. Conventions:
--   * every timestamp is TIMESTAMPTZ (UTC instants; asyncpg treats naive
--     datetimes bound to timestamptz parameters as UTC)
--   * every json payload is JSONB, NOT NULL, defaulting to '{}'
--   * priorities: LOWER numbers are MORE urgent; workers claim prio <= ceiling
--   * job identity is stable across retries: a retry requeues the SAME row
--     and advances run_epoch (checkpoints and history reference one job id
--     forever; run_count, not run_epoch, counts attempts)
--   * 'crashed' is TERMINAL: the job exhausted its retries (the DLQ is
--     `WHERE state = 'crashed'`, not a heuristic)
-- ============================================================================

CREATE TYPE jorbstate AS ENUM (
    'queued',     -- claimable (includes retry-waiting and durable sleep)
    'claimed',    -- taken by a worker, not yet executing
    'running',    -- executing on a worker
    'waiting',    -- blocked on waitfor_job / waitfor_group
    'finished',   -- terminal success
    'crashed',    -- terminal failure after retries exhausted (the DLQ)
    'cancelled'   -- terminal, cancelled by operator or client
);

-- ============================================================================
-- Core job table
-- ============================================================================
CREATE TABLE jorb (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue           TEXT        NOT NULL DEFAULT 'default',
    capability      TEXT,                 -- worker must advertise this to claim
    prio            INTEGER     NOT NULL DEFAULT 100,  -- lower = more urgent
    state           jorbstate   NOT NULL DEFAULT 'queued',
    job_class       TEXT        NOT NULL,
    kwargs          JSONB       NOT NULL DEFAULT '{}',
    admin_data      JSONB       NOT NULL DEFAULT '{}',
    result          JSONB,
    uid             BIGINT,               -- multi-tenancy tag
    tags            JSONB       NOT NULL DEFAULT '{}',  -- caller's own labels

    -- dependency edges
    run_group       BIGINT,
    waitfor_group   BIGINT,
    waitfor_job     BIGINT,
    dag_id          BIGINT,

    -- idempotent enqueue: one queued row per (deadline_key, queue)
    deadline_key    TEXT,

    -- execution bookkeeping
    run_count       INTEGER     NOT NULL DEFAULT 0,
    error_count     INTEGER     NOT NULL DEFAULT 0,
    error_message   TEXT,
    error_backtrace TEXT,
    run_epoch       INTEGER     NOT NULL DEFAULT 0,  -- fencing token (see COMMENT)
    cancel_requested BOOLEAN    NOT NULL DEFAULT FALSE,
    -- demand latch for the jorb_done / jorb_event channels (see the
    -- notification section at the bottom of this file)
    awaited         BOOLEAN     NOT NULL DEFAULT FALSE,

    -- who has it
    claimed_by      BIGINT,               -- jorb_worker.id
    worker_pid      INTEGER,
    worker_host     TEXT,

    -- timing (all timestamptz)
    created         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated         TIMESTAMPTZ NOT NULL DEFAULT now(),
    run_after       TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at      TIMESTAMPTZ,
    started         TIMESTAMPTZ,
    finished        TIMESTAMPTZ,
    timeout_at      TIMESTAMPTZ
);

COMMENT ON TABLE jorb IS 'Jobs. One row per job for its whole life; retries re-queue the same row.';
COMMENT ON COLUMN jorb.prio IS 'Lower numbers are more urgent; workers claim jobs with prio <= their ceiling.';
COMMENT ON COLUMN jorb.claimed_at IS 'When this attempt was admitted by a worker. Rate limits count admissions, not execution starts: started is written after the claim commits, so counting it lets a claim miss the claim before it.';
COMMENT ON COLUMN jorb.run_epoch IS 'Fencing token, NOT an attempt counter (that is run_count). Advances whenever the job enters an attempt (claim) or is abandoned by one (retry/requeue), so a superseded execution may not write results or checkpoints.';
COMMENT ON COLUMN jorb.awaited IS 'Someone has waited on this job (wait_for_result/get_event). Set by the waiter BEFORE it looks at the state, and never cleared: it is the demand signal that switches the jorb_done and jorb_event notifications on for this job, and it costs one HOT update per job that is ever awaited.';
COMMENT ON COLUMN jorb.tags IS 'The CALLER''s labels (customer, region, batch), flat key -> scalar, for filtering jobs by something the application means. Deliberately NOT admin_data: that column is the platform''s own execution config (max_retries, timeout_seconds, save_result, schedule metadata), which nobody filters on, so indexing it would tax every enqueue to make no query faster.';
COMMENT ON COLUMN jorb.waitfor_group IS 'Becomes queued only when ALL jobs with run_group = this value are finished.';
COMMENT ON COLUMN jorb.waitfor_job IS 'Becomes queued only when the job with this id is finished.';

-- the poll/claim path
CREATE INDEX jorb_claim_idx ON jorb (queue, prio, run_after)
    WHERE state = 'queued';
-- rate limiting counts recent admissions per queue
CREATE INDEX jorb_claimed_at_idx ON jorb (queue, claimed_at)
    WHERE claimed_at IS NOT NULL;
-- duration/throughput reporting
CREATE INDEX jorb_started_idx ON jorb (queue, started)
    WHERE started IS NOT NULL;
-- reaper scans
CREATE INDEX jorb_inflight_idx ON jorb (state, updated)
    WHERE state IN ('claimed', 'running');
-- retention: the sweep asks "which terminal jobs aged out?" every cycle, and
-- once it has caught up the honest answer is usually "none". Without this it
-- reads the whole terminal backlog to say so -- measured at 300k rows that is
-- already a full scan, and a busy install keeps orders of magnitude more.
-- Indexed on the expression the sweep actually filters by.
CREATE INDEX jorb_retention_idx ON jorb (COALESCE(finished, updated))
    WHERE state IN ('finished', 'crashed', 'cancelled');
-- reporting windows. Deliberately on `created` and NOT on `updated`:
-- `updated` is rewritten by every state change, so indexing it would add an
-- index write to each of the ~4 updates per job AND block HOT updates on the
-- hottest table in the system -- paying in permanent bloat for a read that
-- happens on a scrape interval. `created` is written once.
CREATE INDEX jorb_created_idx ON jorb (created);
CREATE INDEX jorb_timeout_idx ON jorb (timeout_at)
    WHERE state = 'running' AND timeout_at IS NOT NULL;
-- dependency wakeups
CREATE INDEX jorb_waitfor_job_idx   ON jorb (waitfor_job)   WHERE state = 'waiting';
CREATE INDEX jorb_waitfor_group_idx ON jorb (waitfor_group) WHERE state = 'waiting';
-- Partial like their neighbours, and for the same reason: run_group and uid
-- are NULL on the overwhelming majority of jobs (only grouped work and
-- multi-tenant callers set them), but a plain btree indexes NULLs too. That
-- means an index entry written on every insert and maintained by every
-- vacuum, for rows the index can never usefully answer a question about --
-- pure write amplification on the hottest table in the system.
CREATE INDEX jorb_run_group_idx ON jorb (run_group) WHERE run_group IS NOT NULL;
CREATE INDEX jorb_uid_idx       ON jorb (uid)       WHERE uid IS NOT NULL;
CREATE INDEX jorb_dag_idx           ON jorb (dag_id) WHERE dag_id IS NOT NULL;
-- Caller-supplied labels, and partial for exactly the reason the three above
-- are: almost every job sets no tags at all, and a plain GIN index would
-- still store an entry for each of them -- an object with no keys yields no
-- keys to index, so GIN records it as an empty item purely so that a full
-- index scan can find the row again. That is write amplification on the
-- hottest table in the system in exchange for nothing.
--
-- The predicate keeps the untagged enqueue path -- the hot one -- out of the
-- index entirely, and that is measured, not assumed. At 16 concurrent
-- connections with one transaction per job, untagged enqueue is unchanged by
-- this index existing (28.7k vs 28.9k jobs/s, medians of nine interleaved
-- pj-bench pairs, which is noise on a shared box). Enqueue WITH tags
-- populated measures 0.93-1.04x of untagged even when every job carries a
-- DISTINCT tag value, GIN's pessimal case: fastupdate parks new entries in
-- the pending list and the merge is autovacuum's problem, not the enqueuing
-- transaction's. tests/test_job_tags.py holds both measurements, and asserts
-- the index does not grow at all when 10,000 untagged jobs are inserted.
--
-- THE COST OF PARTIAL, which every caller has to pay attention to: a query
-- may use a partial index only when its own clauses IMPLY the predicate, and
-- PostgreSQL proves that syntactically. It cannot derive `tags <> '{}'` from
-- `tags @> '{"customer":"acme"}'`, so a filter that omits the predicate is
-- correct and sequentially scans the table. Every tag filter in this codebase
-- is therefore built by client.tags_filter_sql, which emits both clauses.
CREATE INDEX jorb_tags_idx ON jorb USING GIN (tags) WHERE tags <> '{}';
-- idempotent enqueue
CREATE UNIQUE INDEX jorb_deadline_idx ON jorb (deadline_key, queue)
    WHERE state = 'queued' AND deadline_key IS NOT NULL;

-- ----------------------------------------------------------------------------
-- Autovacuum, tuned for this table's write pattern rather than left at the
-- server defaults. A job costs ~4 row versions (insert, claim, run, terminal),
-- so a busy install produces dead tuples in the millions per hour. The default
-- scale factor of 0.2 means "wait until 20% of the table is garbage", which on
-- a large jorb is both far too late and then far too much work at once; the
-- claim index bloats in the meantime.
--
-- fillfactor leaves room on each page for an updated row version to live
-- beside its original, which is what allows a HOT update -- an update that
-- does not have to touch every index. That is why `updated` is not indexed.
ALTER TABLE jorb SET (
    autovacuum_vacuum_scale_factor  = 0.02,
    autovacuum_vacuum_threshold     = 1000,
    autovacuum_analyze_scale_factor = 0.02,
    autovacuum_vacuum_cost_limit    = 2000,
    fillfactor                      = 85
);

-- ============================================================================
-- Queue control plane (live-tunable; absent row = defaults)
-- ============================================================================
CREATE TABLE jorb_queue (
    name                TEXT PRIMARY KEY,
    paused              BOOLEAN     NOT NULL DEFAULT FALSE,
    max_concurrency     INTEGER,              -- NULL = unlimited (claimed+running cap)
    rate_limit          INTEGER,              -- max starts per rate_period; NULL = unlimited
    rate_period_seconds DOUBLE PRECISION NOT NULL DEFAULT 60,
    created             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated             TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE jorb_queue IS 'Per-queue controls enforced by claim_jorb(); rows are optional (missing queue = unpaused, unlimited).';

-- ============================================================================
-- The claim path
-- ============================================================================
-- Claiming lives in the database, not in the worker, so that the queue's
-- controls are enforced for EVERY claimer rather than only for clients that
-- remember to enforce them.
--
-- Why the advisory lock: under READ COMMITTED a statement sees the snapshot
-- taken when it began, so two simultaneous claims cannot see each other's
-- uncommitted rows and a cap of 1 would admit both. Serializing claims for a
-- controlled queue fixes that -- and because PL/pgSQL takes a new snapshot per
-- statement, the counts below run AFTER the lock and therefore see every claim
-- that has already committed. Uncontrolled queues (the common case) never take
-- the lock and keep the lock-free fast path.

-- Take the per-queue claim lock, or give up after a BOUNDED wait.
--
-- The serialising lock has to be bounded: a claim held open by a slow or
-- stuck transaction must never freeze the whole queue. An immediate try-lock
-- bounds it at zero, and that is what used to be here -- but losing a
-- try-lock is not free for the thing that actually loses it. A CLIENT that
-- retries in a loop pays one wasted round trip; a WORKER (see pj.py's run
-- loop) treats an empty claim as "this queue has no work", publishes idle
-- demand -- switching this queue's enqueue notifications back on for every
-- producer -- and then parks for checkInterval, five seconds by default,
-- waiting for a wakeup that is not coming because the work it wanted was
-- enqueued before it went to sleep.
--
-- Measured with four real workers on a queue holding 40 jobs under a cap that
-- could never bind: the try-lock let ONE of the four ever claim anything --
-- whoever won kept winning and the other three slept on a full queue. Waiting
-- for the lock puts claimers in the lock manager's FIFO queue instead, and
-- all four work. lock_timeout keeps the give-up guarantee: the wait is capped,
-- the timeout arrives as 55P03 (lock_not_available), and it is caught here and
-- reported as "nothing claimable" exactly as a lost try-lock was.
--
-- What this is NOT is a throughput fix, and it must not be sold as one. A
-- claimer that lost the try-lock held no lock, so its retries were wasted
-- BESIDE the critical section, not inside it: capped throughput is
-- 1/(critical section) either way. Measured against the try-lock in the same
-- run it lands at 0.96x on an idle box and 2.1x on a saturated one, with 98%+
-- of the round trips gone in both -- which is the shape you get when the
-- removed work was never on the critical path but was still competing for CPU
-- with the thing that was. Neither number is the ceiling moving. Raising the
-- capped ceiling means a cheaper critical section, or more than one claim per
-- acquisition (batching) -- a worker-model change, not a lock change.
--
-- Why its own function rather than SET LOCAL inside claim_jorb: a function's
-- SET clause is applied on entry and restored by PostgreSQL on exit, error or
-- not, so the timeout covers the lock acquisition and NOTHING else. Putting
-- it on claim_jorb would also arm it on the claiming UPDATE, whose
-- SKIP LOCKED probe can briefly re-contend for the row it picked, turning a
-- momentary wait into an error the worker never asked to handle. SET LOCAL
-- would instead leak the timeout into the caller's remaining transaction.
--
-- Why 50 ms: it is the maximum a claimer stalls, so it trades claim latency
-- against wasted round trips, and the sweep in tests/test_claim_contention.py
-- puts the knee well below it -- eight claimers waste 2,710 round trips per
-- 2,000 claims at 1 ms (the try-lock's regime), 86 at 5 ms, 7 at 20 ms, 2 at
-- 50 ms, 0 at 200 ms, with claim rate flat from 5 ms up. 50 ms buys the last
-- of the waste at a stall a busy worker can absorb -- a claim wedged open by a
-- stuck transaction degrades it to 20 attempts a second instead of hanging it
-- -- and is 1% of the 5 s idle poll, so an idle worker cannot notice it. 200 ms
-- would quadruple the worst-case stall to save two round trips in two thousand.
CREATE FUNCTION claim_queue_lock(p_queue TEXT) RETURNS BOOLEAN
LANGUAGE plpgsql
SET lock_timeout = '50ms'
AS $$
BEGIN
    PERFORM pg_advisory_xact_lock(hashtext('pyjobby.claim:' || p_queue));
    -- Acquired inside this block's implicit subtransaction, which commits
    -- with the block: PostgreSQL transfers the lock to the parent
    -- transaction, so it is held for the rest of the claim exactly as a
    -- lock taken at the top level would be.
    RETURN TRUE;
EXCEPTION WHEN lock_not_available THEN
    -- Timed out: nothing was acquired, so there is nothing to release.
    RETURN FALSE;
END;
$$;

COMMENT ON FUNCTION claim_queue_lock IS 'Serialise claims for one controlled queue, waiting at most lock_timeout (50ms). TRUE = held for the rest of the transaction; FALSE = timed out, treat the queue as busy.';

CREATE FUNCTION claim_jorb(
    p_queue        TEXT,
    p_capabilities TEXT[],
    p_max_prio     INTEGER,
    p_worker_pid   INTEGER,
    p_worker_host  TEXT,
    p_worker_id    BIGINT
) RETURNS SETOF jorb
LANGUAGE plpgsql AS $$
DECLARE
    q jorb_queue%ROWTYPE;
BEGIN
    SELECT * INTO q FROM jorb_queue WHERE name = p_queue;

    IF COALESCE(q.paused, FALSE) THEN
        RETURN;
    END IF;

    IF q.max_concurrency IS NOT NULL OR q.rate_limit IS NOT NULL THEN
        -- Bounded on purpose (see claim_queue_lock): wait a little to be
        -- served in order, but never longer than the timeout, so a claim held
        -- open by a slow or stuck transaction can never freeze the queue.
        IF NOT claim_queue_lock(p_queue) THEN
            RETURN;
        END IF;

        IF q.max_concurrency IS NOT NULL AND q.max_concurrency <= (
               SELECT count(*) FROM jorb
               WHERE queue = p_queue AND state IN ('claimed', 'running')) THEN
            RETURN;
        END IF;

        IF q.rate_limit IS NOT NULL AND q.rate_limit <= (
               SELECT count(*) FROM jorb
               WHERE queue = p_queue
                 AND claimed_at > now()
                     - make_interval(secs => q.rate_period_seconds)) THEN
            RETURN;
        END IF;
    END IF;

    RETURN QUERY
    UPDATE jorb
       SET state      = 'claimed',
           worker_pid = p_worker_pid,
           worker_host= p_worker_host,
           claimed_by = p_worker_id,
           claimed_at = now(),
           run_count  = run_count + 1,
           run_epoch  = run_epoch + 1,
           updated    = now()
     WHERE id = (
           SELECT j.id FROM jorb j
            WHERE j.queue = p_queue
              AND (j.capability = ANY(p_capabilities) OR j.capability IS NULL)
              AND j.prio <= p_max_prio
              AND j.run_after <= now()
              AND j.state = 'queued'
            ORDER BY j.prio, j.run_after
              FOR UPDATE OF j SKIP LOCKED
            LIMIT 1)
    RETURNING *;
END;
$$;

COMMENT ON FUNCTION claim_jorb IS 'Atomically admit at most one queued job for a worker, enforcing the queue pause/concurrency/rate controls. Returns zero rows when nothing is claimable.';

-- ============================================================================
-- Worker registry (exact liveness; replaces pid/grace guessing)
-- ============================================================================
CREATE TABLE jorb_worker (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host         TEXT        NOT NULL,
    pid          INTEGER     NOT NULL,
    queue        TEXT        NOT NULL,
    capabilities TEXT[]      NOT NULL DEFAULT '{}',
    version      TEXT,
    started      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen    TIMESTAMPTZ NOT NULL DEFAULT now(),
    shutdown_at  TIMESTAMPTZ,          -- set on graceful exit
    -- demand signal for the jorb_enqueued channel (see the notification
    -- section at the bottom of this file)
    idle         BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE INDEX jorb_worker_live_idx ON jorb_worker (last_seen) WHERE shutdown_at IS NULL;

-- The enqueue trigger's gate: "is anybody on this queue parked, waiting to
-- be woken?" Partial so the index holds ONLY parked workers -- which is
-- near-empty exactly when the system is busy and the lookup is hottest.
CREATE INDEX jorb_worker_idle_idx ON jorb_worker (queue)
    WHERE idle AND shutdown_at IS NULL;

COMMENT ON TABLE jorb_worker IS 'One row per worker process; heartbeats update last_seen. A live worker = shutdown_at IS NULL and recent last_seen.';
COMMENT ON COLUMN jorb_worker.idle IS 'This worker found nothing to claim and is now parked on the jorb_enqueued wakeup. Set BEFORE the claim that finds nothing, cleared when it claims again; cleared on graceful shutdown and by the monitor when it retires a dead worker, so a crashed worker cannot leave notifications switched on forever.';

-- ============================================================================
-- DXE: step checkpoints (durable execution)
-- ============================================================================
CREATE TABLE jorb_step (
    job_id    BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    step_seq  INTEGER     NOT NULL,
    name      TEXT        NOT NULL,
    output    JSONB,
    error     TEXT,                    -- recorded exception; replay re-raises
    run_epoch INTEGER     NOT NULL,    -- which attempt produced this checkpoint
    started   TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished  TIMESTAMPTZ,
    PRIMARY KEY (job_id, step_seq)
);

COMMENT ON TABLE jorb_step IS 'DXE checkpoints: a completed step is never re-executed on retry/resume; a name mismatch at a step_seq means nondeterministic job code.';

-- ============================================================================
-- DXE: key/value events (job publishes, anyone reads/awaits)
-- ============================================================================
CREATE TABLE jorb_event (
    job_id  BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    key     TEXT        NOT NULL,
    value   JSONB       NOT NULL,
    updated TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (job_id, key)
);

-- ============================================================================
-- DXE: durable job-to-job messages
-- ============================================================================
CREATE TABLE jorb_mailbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dest_job_id BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    topic       TEXT,
    message     JSONB       NOT NULL,
    created     TIMESTAMPTZ NOT NULL DEFAULT now(),
    consumed_at TIMESTAMPTZ
);

CREATE INDEX jorb_mailbox_pending_idx ON jorb_mailbox (dest_job_id, topic, id)
    WHERE consumed_at IS NULL;

-- Retention drives off consumed messages, every cycle, forever. A long-lived
-- job reads mail for months, so the job-scoped cascade never reaches them and
-- this is the only thing that does -- unindexed it would scan the whole
-- mailbox each pass and get slower forever.
CREATE INDEX jorb_mailbox_consumed_idx ON jorb_mailbox (consumed_at)
    WHERE consumed_at IS NOT NULL;

-- ============================================================================
-- Transition history (first-class audit; retries keep one job id)
-- ============================================================================
CREATE TABLE jorb_history (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- cascades like every other child of jorb: history is the biggest of
    -- them, so without the key retention would free the small tables and
    -- leave the largest one growing forever
    job_id  BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    event   TEXT        NOT NULL,  -- enqueued|claimed|started|finished|retrying|crashed|cancelled|timeout|requeued|recovered
    detail  JSONB       NOT NULL DEFAULT '{}'
);

CREATE INDEX jorb_history_job_idx ON jorb_history (job_id, id);

-- Append-only until retention deletes in bulk, so it needs a low scale factor
-- to clean up promptly after a sweep, but no fillfactor headroom.
ALTER TABLE jorb_history SET (
    autovacuum_vacuum_scale_factor = 0.05,
    autovacuum_vacuum_threshold    = 5000,
    autovacuum_vacuum_cost_limit   = 2000
);


COMMENT ON TABLE jorb_history IS 'Every state transition with worker/epoch/error detail; the per-attempt audit trail (jobs keep one row in jorb for life).';

-- ============================================================================
-- Recurring schedules (cron) + execution log
-- ============================================================================
CREATE TABLE jorb_schedule (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      TEXT    NOT NULL UNIQUE,
    description               TEXT,
    job_class                 TEXT    NOT NULL,
    kwargs                    JSONB   NOT NULL DEFAULT '{}',
    queue                     TEXT    NOT NULL DEFAULT 'default',
    prio                      INTEGER NOT NULL DEFAULT 100,
    capability                TEXT,
    cron_expr                 TEXT    NOT NULL,
    timezone                  TEXT    NOT NULL DEFAULT 'UTC',
    enabled                   BOOLEAN NOT NULL DEFAULT TRUE,
    max_concurrent_jobs       INTEGER NOT NULL DEFAULT 1,
    jitter_seconds            INTEGER NOT NULL DEFAULT 0,
    backpressure_threshold    INTEGER          DEFAULT 1000,
    circuit_breaker_threshold INTEGER NOT NULL DEFAULT 5,
    consecutive_failures      INTEGER NOT NULL DEFAULT 0,
    next_run                  TIMESTAMPTZ NOT NULL,
    last_run                  TIMESTAMPTZ,
    last_success              TIMESTAMPTZ,
    last_failure              TIMESTAMPTZ,
    run_count                 BIGINT  NOT NULL DEFAULT 0,
    success_count             BIGINT  NOT NULL DEFAULT 0,
    failure_count             BIGINT  NOT NULL DEFAULT 0,
    skip_count                BIGINT  NOT NULL DEFAULT 0,
    created                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by                TEXT
);

CREATE INDEX jorb_schedule_due_idx ON jorb_schedule (next_run) WHERE enabled;

CREATE TABLE jorb_schedule_log (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id            BIGINT NOT NULL REFERENCES jorb_schedule (id) ON DELETE CASCADE,
    schedule_name          TEXT   NOT NULL,
    scheduled_time         TIMESTAMPTZ NOT NULL,
    actual_time            TIMESTAMPTZ NOT NULL DEFAULT now(),
    result                 TEXT   NOT NULL,  -- success|failure|skipped
    skip_reason            TEXT,
    job_id                 BIGINT,
    error_message          TEXT,
    duration_ms            INTEGER,
    queue_depth_at_run     INTEGER,
    concurrent_jobs_at_run INTEGER,
    jitter_applied_seconds INTEGER
);

CREATE INDEX jorb_schedule_log_idx ON jorb_schedule_log (schedule_id, id);

-- ============================================================================
-- DAG orchestration
-- ============================================================================
CREATE TABLE jorb_dag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT,
    created     TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed   TIMESTAMPTZ,
    metadata    JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE jorb_dependencies (
    job_id     BIGINT NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    depends_on BIGINT NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    PRIMARY KEY (job_id, depends_on)
);

-- The primary key leads with job_id, so THAT cascade is indexed; depends_on
-- is a second foreign key to the same table and Postgres indexes neither
-- automatically. Without this, deleting a job sequentially scans this table
-- looking for edges that point at it -- once per deleted job, which is
-- exactly what retention does in bulk.
CREATE INDEX jorb_dependencies_depends_on_idx ON jorb_dependencies (depends_on);

ALTER TABLE jorb ADD CONSTRAINT jorb_dag_fk
    FOREIGN KEY (dag_id) REFERENCES jorb_dag (id) ON DELETE SET NULL;

CREATE VIEW jorb_dag_status AS
    SELECT d.id AS dag_id,
           d.name,
           d.created,
           d.completed,
           count(j.id)                                            AS total_jobs,
           count(j.id) FILTER (WHERE j.state = 'finished')        AS finished_jobs,
           count(j.id) FILTER (WHERE j.state = 'crashed')         AS crashed_jobs,
           count(j.id) FILTER (WHERE j.state = 'cancelled')       AS cancelled_jobs,
           count(j.id) FILTER (WHERE j.state IN ('queued','claimed','running','waiting')) AS pending_jobs
    FROM jorb_dag d
    LEFT JOIN jorb j ON j.dag_id = d.id
    GROUP BY d.id;

CREATE VIEW jorb_dag_timeline AS
    SELECT j.dag_id,
           j.id AS job_id,
           j.job_class,
           j.state,
           j.started,
           j.finished,
           EXTRACT(EPOCH FROM (j.finished - j.started)) AS duration_seconds
    FROM jorb j
    WHERE j.dag_id IS NOT NULL;

-- ============================================================================
-- Notifications: one mechanism, one gate, one place to change it
-- ============================================================================
-- WHY NOTIFY IS EXPENSIVE. Committing a transaction that issued a NOTIFY
-- takes a GLOBAL exclusive lock, held until that commit completes (and
-- fsyncs). Notifications must be delivered in commit order, and commit order
-- is not established until commits finish -- so PostgreSQL serialises every
-- NOTIFY-bearing commit against every other one, defeating group commit.
-- Measured on this schema at 16 concurrent connections, one transaction per
-- job (the production enqueue shape): 12,873 jobs/s as shipped versus
-- 37,803 jobs/s with the NOTIFY triggers off. Two thirds of concurrent write
-- throughput, spent on notifications. It is invisible to a serial benchmark
-- (nothing to serialise against) and invisible to a bulk insert (one lock
-- amortised over the batch).
--
-- The lock is per COMMIT, not per notification: a transaction that notifies
-- three times pays exactly what a transaction that notifies once pays. So
-- trimming channels buys nothing. The only thing that helps is NOT NOTIFYING
-- -- and almost every notification this schema used to send was unnecessary,
-- because a notification exists to wake a consumer and under load the
-- consumers are never asleep.
--
-- THE POLICY (uniform, every channel): a notification is emitted only when a
-- consumer has REGISTERED DEMAND for its topic, and demand is registered
-- BEFORE that consumer's last look at the underlying state. The cost then
-- scales inversely with load, which is exactly right: when the system is
-- busy nobody is parked and the notification is pure overhead, paid at the
-- global commit lock precisely in the regime where it hurts most; when the
-- system is idle, latency matters but volume is low and the lock is free.
--
-- THE MECHANISM (uniform): every channel goes through jorb_notify() below.
-- The channel's topic, its demand kind and its payload are declared once, in
-- that one function, so a change to the gate or the payload convention is
-- made once instead of seven times.
--
-- THE DEMAND STORAGE (deliberately NOT uniform): each channel uses the
-- cheapest correct signal for its own shape. Uniform policy, not uniform
-- cost -- an expensive lookup forced onto the write path in the name of
-- symmetry would give back what the gate just won.
--
--   channel            demand kind    what "somebody is waiting" means
--   ------------------ -------------- --------------------------------------
--   jorb_enqueued      idle_worker    a worker on that queue is parked
--   jorb_done          row_local      jorb.awaited on the very row changing
--   jorb_event         job_awaited    jorb.awaited on the publishing job
--   jorb_cancel        row_local      the job is actually running
--   schedule_executed  ungated        (see below)
--
-- WHEN A CHANNEL MUST NOT BE GATED. A gate trades a notification for the
-- consumer's polling fallback. A consumer with NO fallback cannot pay that:
-- a skipped notification is an event it never learns about, not an event it
-- learns about late. schedule_executed feeds the push-only websocket
-- dashboard, so it stays ungated on purpose -- and it costs nothing, because
-- it fires once per schedule EXECUTION (cron rate, not job rate) on
-- jorb_schedule_log rather than on any hot path.
--
-- THE CHANNEL THAT WAS DELETED RATHER THAN GATED. job_state_change fired on
-- EVERY state transition (queued->claimed->running->finished, four per job),
-- ungated, and pushed each one to the websocket dashboard. Once every other
-- channel was gated it was the entire remaining bill: the commit lock is
-- taken per COMMIT, so one ungated channel costs exactly what seven cost,
-- and deleting it is worth 2.6-2.9x on the completion path (measured across
-- runs in tests/test_notify_gating.py, which rebuilds the deleted trigger so
-- the "before" number stays measurable).
--
-- It could not be gated, because its consumer was push-only: a gate would
-- have DROPPED dashboard events, not delayed them. So the consumer got a
-- different mechanism instead. At the reference workload the channel was
-- ~830 individual transitions per second, which no dashboard renders and no
-- human reads, so pyjobby/websocket_server.py now POLLS aggregates on an
-- interval -- one index-backed query per second, shared by every connected
-- dashboard, and none at all while nobody is subscribed. A bounded,
-- predictable cost replaced one that scaled with job throughput. A client
-- that needs a specific job watches THAT job, which rides jorb_done and is
-- gated on jorb.awaited like any other waiter.
--
-- A CHANNEL WITH NO CONSUMER AT ALL. jorb_mailbox is gone. Nothing ever
-- LISTENed on it: Job.recv() polls jorb_mailbox directly every 250 ms (see
-- pyjobby/pj.py). It was a NOTIFY, and therefore a global commit lock, on
-- every durable message send, delivered to nobody.
CREATE FUNCTION jorb_notify() RETURNS trigger AS $$
DECLARE
    channel CONSTANT TEXT := TG_ARGV[0];
    demand  CONSTANT TEXT := TG_ARGV[1];
    topic   TEXT;
    wanted  BOOLEAN;
    payload TEXT;
BEGIN
    -- 1. The topic: the finest-grained thing a consumer can register demand
    --    for. One column read, and nothing else, because everything after
    --    this point is work the write path may turn out not to need.
    CASE channel
        WHEN 'jorb_enqueued'     THEN topic := NEW.queue;
        WHEN 'jorb_done'         THEN topic := NEW.id::TEXT;
        WHEN 'jorb_cancel'       THEN topic := NEW.id::TEXT;
        WHEN 'jorb_event'        THEN topic := NEW.job_id::TEXT;
        WHEN 'schedule_executed' THEN topic := NEW.schedule_id::TEXT;
        ELSE RAISE EXCEPTION 'jorb_notify: unknown channel %', channel;
    END CASE;

    -- 2. The gate. Every demand predicate in the system is enumerated here.
    CASE demand
        -- The trigger's WHEN clause IS the gate: the demand signal lives on
        -- the very row being written, so the executor evaluates it for free
        -- and this function is not even reached when nobody is waiting.
        WHEN 'row_local' THEN
            wanted := TRUE;
        -- No gate, and that is a decision, not an oversight: this channel's
        -- consumer has no polling fallback.
        WHEN 'ungated' THEN
            wanted := TRUE;
        -- Some worker on this queue is parked on the wakeup. Indexed by
        -- jorb_worker_idle_idx, over a table with one row per worker
        -- process, whose idle subset is empty exactly when we are busy.
        WHEN 'idle_worker' THEN
            wanted := EXISTS (SELECT 1 FROM jorb_worker w
                               WHERE w.queue = topic
                                 AND w.idle
                                 AND w.shutdown_at IS NULL);
        -- A client is (or was) blocked waiting on this job. One primary-key
        -- probe on jorb.
        WHEN 'job_awaited' THEN
            wanted := EXISTS (SELECT 1 FROM jorb j
                               WHERE j.id = topic::BIGINT AND j.awaited);
        ELSE RAISE EXCEPTION 'jorb_notify: unknown demand kind %', demand;
    END CASE;

    IF NOT wanted THEN
        RETURN NULL;
    END IF;

    -- 3. The payload. Built only once the gate has said somebody wants it.
    CASE channel
        WHEN 'jorb_enqueued' THEN
            payload := NEW.queue;
        WHEN 'jorb_cancel' THEN
            payload := NEW.id::TEXT;
        WHEN 'jorb_done' THEN
            payload := json_build_object(
                'id', NEW.id, 'state', NEW.state)::TEXT;
        WHEN 'jorb_event' THEN
            payload := json_build_object(
                'job_id', NEW.job_id, 'key', NEW.key)::TEXT;
        WHEN 'schedule_executed' THEN
            payload := json_build_object(
                'schedule_id', NEW.schedule_id,
                'schedule_name', NEW.schedule_name,
                'result', NEW.result,
                'job_id', NEW.job_id)::TEXT;
    END CASE;

    PERFORM pg_notify(channel, payload);
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION jorb_notify IS 'The one notification trigger. TG_ARGV = (channel, demand kind); topic, gate and payload for every channel are declared in its body.';

-- ----------------------------------------------------------------------------
-- jorb_enqueued -- wake a parked worker when work arrives on its queue
-- ----------------------------------------------------------------------------
-- WHY IT IS DEFERRED. This is a CONSTRAINT TRIGGER so the gate is evaluated
-- at COMMIT rather than at the end of the INSERT. The demand signal lives on
-- another table (jorb_worker), so unlike jorb_done there is no row lock to
-- order the two writers, and an ordinary AFTER trigger would decide whether
-- to notify from a snapshot taken when the statement ran -- possibly long
-- before the insert became visible. enqueue_in_transaction(), enqueue_batch()
-- and DAG creation all insert inside a transaction that stays open, so
-- "decide at INSERT, deliver at COMMIT" would drop the wakeup for every job
-- enqueued transactionally while a worker parked. Deferring makes the
-- decision and the delivery the same instant.
--
-- WHY NO WAKEUP IS LOST (the ordering argument; the worker's half is in
-- JobSystem.run/_set_idle):
--
--   The worker publishes idle = TRUE and only THEN makes its last claim
--   attempt, so for any inserted job J and any worker W:
--
--     * J's gate runs after W's idle=TRUE commits  ->  the EXISTS sees W,
--       the notification is emitted, W wakes.
--     * J commits before W's last claim takes its snapshot  ->  W claims J
--       and never parks in the first place.
--
--   Those two cases overlap and cover everything except one window: J's gate
--   ran (at J's commit) before W published idle, AND J was still not visible
--   when W's claim took its snapshot microseconds later. That is the gap
--   between J's WAL flush completing and J leaving the proc array, and it is
--   covered by the worker's unconditional poll every checkInterval (5s
--   default). Reversing the worker's order -- claim first, then publish idle
--   -- would open that window to the whole width of a claim round trip, on
--   every park, which is the mistake this comment exists to prevent.
CREATE CONSTRAINT TRIGGER jorb_enqueued_notify
    AFTER INSERT OR UPDATE OF state ON jorb
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW WHEN (NEW.state = 'queued')
    EXECUTE FUNCTION jorb_notify('jorb_enqueued', 'idle_worker');

-- ----------------------------------------------------------------------------
-- jorb_done -- tell a wait_for_result() caller its job reached a terminal state
-- ----------------------------------------------------------------------------
-- WHY NO WAKEUP IS LOST, and why this one needs no deferral: the demand
-- signal (jorb.awaited) is on the SAME ROW as the state change, so the two
-- writers take the same row lock and PostgreSQL orders them for us.
--
--   * waiter's UPDATE awaited=TRUE commits first -> the worker's terminal
--     UPDATE either saw it already, or blocked on the row lock and then
--     re-evaluated against the newest version, where awaited is TRUE. The
--     WHEN clause fires, the waiter is notified.
--   * terminal UPDATE commits first -> the waiter's UPDATE necessarily
--     commits after it, so the waiter's very next state read (its first
--     check, which always runs before it waits) sees the terminal state and
--     it never waits at all.
--
-- No third case exists: one of the two commits first. The client's 2s
-- fallback poll (JobClient._LISTEN_POLL_INTERVAL) is a safety net that this
-- argument does not need.
CREATE TRIGGER jorb_done_notify
    AFTER UPDATE OF state ON jorb
    FOR EACH ROW WHEN (NEW.state IN ('finished', 'crashed', 'cancelled')
                       AND NEW.awaited)
    EXECUTE FUNCTION jorb_notify('jorb_done', 'row_local');

-- ----------------------------------------------------------------------------
-- jorb_cancel -- tell the executing worker a running job should stop
-- ----------------------------------------------------------------------------
-- Already demand-gated, and always was: nobody listens for the cancellation
-- of a job that is not running (a queued job is cancelled by the same
-- statement that requests it), so `NEW.state = 'running'` IS the demand
-- signal, evaluated row-locally by the executor. It is not gated any
-- further, because the worker's cancellation listener has no polling
-- fallback -- a skipped jorb_cancel is a cancellation that never happens,
-- not one that happens late. It costs nothing to leave alone: it fires at
-- operator rate, not at job rate.
CREATE TRIGGER jorb_cancel_notify
    AFTER UPDATE OF cancel_requested ON jorb
    FOR EACH ROW WHEN (NEW.cancel_requested AND NEW.state = 'running')
    EXECUTE FUNCTION jorb_notify('jorb_cancel', 'row_local');

-- ----------------------------------------------------------------------------
-- jorb_event -- wake get_event() waiters when a job publishes a key
-- ----------------------------------------------------------------------------
-- The demand signal is jorb.awaited, one primary-key probe away, because the
-- waiter registers before the key exists: get_event() commonly waits for a
-- key the job has not published yet, so there is no jorb_event row to hang a
-- row-local flag on. That means no row lock orders the two writers, so the
-- ordering argument is the weaker one: a client that sets awaited while a
-- set_event() is mid-commit can miss that one notification and learns about
-- the key from JobClient's 2s fallback poll instead. Bounded latency on a
-- race, never a lost value -- the event itself is durable in jorb_event.
CREATE TRIGGER jorb_event_notify
    AFTER INSERT OR UPDATE ON jorb_event
    FOR EACH ROW EXECUTE FUNCTION jorb_notify('jorb_event', 'job_awaited');

-- ----------------------------------------------------------------------------
-- (deleted) job_state_change -- the dashboard firehose
-- ----------------------------------------------------------------------------
-- Deliberately absent, and NOT to be re-added. It fired on every state
-- transition and was the last ungated NOTIFY in the system, which made it
-- the whole remaining commit-lock bill: with it gone, the CLAIM and COMPLETE
-- paths stop paying the lock the ENQUEUE path already stopped paying. See
-- "THE CHANNEL THAT WAS DELETED RATHER THAN GATED" above for why deletion
-- rather than a gate, and where its consumer gets its data now.

-- ============================================================================
-- DAG completion: stamped when a DAG's last job reaches a terminal state
-- ============================================================================
-- Recorded by trigger (like history) so every writer — worker, monitor,
-- admin API — keeps jorb_dag.completed truthful without having to know
-- about DAGs.
CREATE FUNCTION complete_jorb_dag() RETURNS trigger AS $$
BEGIN
    IF NEW.dag_id IS NOT NULL THEN
        UPDATE jorb_dag d
        SET completed = now()
        WHERE d.id = NEW.dag_id
          AND d.completed IS NULL
          AND NOT EXISTS (
              SELECT 1 FROM jorb j
              WHERE j.dag_id = NEW.dag_id
                AND j.state NOT IN ('finished', 'crashed', 'cancelled')
          );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER jorb_dag_complete
    AFTER UPDATE OF state ON jorb
    FOR EACH ROW
    WHEN (NEW.state IN ('finished', 'crashed', 'cancelled')
          AND NEW.dag_id IS NOT NULL)
    EXECUTE FUNCTION complete_jorb_dag();

-- ============================================================================
-- History recording: one trigger, every writer covered
-- ============================================================================
-- The worker, monitor, scheduler, admin API, and websocket server all mutate
-- jorb; recording transitions here means none of them can forget to.
CREATE FUNCTION record_jorb_history() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO jorb_history (job_id, event, detail)
        VALUES (NEW.id, 'enqueued', jsonb_build_object(
            'queue', NEW.queue, 'job_class', NEW.job_class,
            'state', NEW.state, 'prio', NEW.prio));
    ELSIF OLD.state IS DISTINCT FROM NEW.state THEN
        INSERT INTO jorb_history (job_id, event, detail)
        VALUES (NEW.id, NEW.state::text, jsonb_build_object(
            'from', OLD.state,
            'run_epoch', NEW.run_epoch,
            'run_count', NEW.run_count,
            'error_count', NEW.error_count,
            'worker_host', NEW.worker_host,
            'worker_pid', NEW.worker_pid,
            'error', CASE WHEN NEW.state IN ('queued','crashed')
                          THEN NEW.error_message END));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER jorb_history_record
    AFTER INSERT OR UPDATE OF state ON jorb
    FOR EACH ROW EXECUTE FUNCTION record_jorb_history();

-- Dashboard schedule execution feed. UNGATED because its consumer is
-- push-only (no polling fallback), and affordable because it fires once per
-- schedule EXECUTION -- cron rate, not job rate -- on jorb_schedule_log
-- rather than on any hot path.
CREATE TRIGGER schedule_executed_notify
    AFTER INSERT ON jorb_schedule_log
    FOR EACH ROW EXECUTE FUNCTION jorb_notify('schedule_executed', 'ungated');
