-- ============================================================================
-- pyjobby unified schema v1
-- ============================================================================
-- Forward-only canonical schema. Conventions:
--   * every timestamp is TIMESTAMPTZ (UTC instants; asyncpg treats naive
--     datetimes bound to timestamptz parameters as UTC)
--   * every json payload is JSONB, NOT NULL, defaulting to '{}'
--   * priorities: LOWER numbers are MORE urgent; workers claim prio <= ceiling
--   * job identity is stable across retries: a retry requeues the SAME row
--     and advances run_epoch (checkpoints and history reference one job id
--     forever; run_count, not run_epoch, counts attempts)
--   * 'crashed' is TERMINAL: the job exhausted its retries (the DLQ is
--     `WHERE state = 'crashed'`, not a heuristic)
-- ============================================================================

CREATE TYPE jorbstate AS ENUM (
    'queued',     -- claimable (includes retry-waiting and durable sleep)
    'claimed',    -- taken by a worker, not yet executing
    'running',    -- executing on a worker
    'waiting',    -- blocked on waitfor_job / waitfor_group
    'finished',   -- terminal success
    'crashed',    -- terminal failure after retries exhausted (the DLQ)
    'cancelled'   -- terminal, cancelled by operator or client
);

-- ============================================================================
-- Core job table
-- ============================================================================
CREATE TABLE jorb (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue           TEXT        NOT NULL DEFAULT 'default',
    capability      TEXT,                 -- worker must advertise this to claim
    prio            INTEGER     NOT NULL DEFAULT 100,  -- lower = more urgent
    state           jorbstate   NOT NULL DEFAULT 'queued',
    job_class       TEXT        NOT NULL,
    kwargs          JSONB       NOT NULL DEFAULT '{}',
    admin_data      JSONB       NOT NULL DEFAULT '{}',
    result          JSONB,
    uid             BIGINT,               -- multi-tenancy tag

    -- dependency edges
    run_group       BIGINT,
    waitfor_group   BIGINT,
    waitfor_job     BIGINT,
    dag_id          BIGINT,

    -- idempotent enqueue: one queued row per (deadline_key, queue)
    deadline_key    TEXT,

    -- execution bookkeeping
    run_count       INTEGER     NOT NULL DEFAULT 0,
    error_count     INTEGER     NOT NULL DEFAULT 0,
    error_message   TEXT,
    error_backtrace TEXT,
    run_epoch       INTEGER     NOT NULL DEFAULT 0,  -- fencing token (see COMMENT)
    cancel_requested BOOLEAN    NOT NULL DEFAULT FALSE,

    -- who has it
    claimed_by      BIGINT,               -- jorb_worker.id
    worker_pid      INTEGER,
    worker_host     TEXT,

    -- timing (all timestamptz)
    created         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated         TIMESTAMPTZ NOT NULL DEFAULT now(),
    run_after       TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at      TIMESTAMPTZ,
    started         TIMESTAMPTZ,
    finished        TIMESTAMPTZ,
    timeout_at      TIMESTAMPTZ
);

COMMENT ON TABLE jorb IS 'Jobs. One row per job for its whole life; retries re-queue the same row.';
COMMENT ON COLUMN jorb.prio IS 'Lower numbers are more urgent; workers claim jobs with prio <= their ceiling.';
COMMENT ON COLUMN jorb.claimed_at IS 'When this attempt was admitted by a worker. Rate limits count admissions, not execution starts: started is written after the claim commits, so counting it lets a claim miss the claim before it.';
COMMENT ON COLUMN jorb.run_epoch IS 'Fencing token, NOT an attempt counter (that is run_count). Advances whenever the job enters an attempt (claim) or is abandoned by one (retry/requeue), so a superseded execution may not write results or checkpoints.';
COMMENT ON COLUMN jorb.waitfor_group IS 'Becomes queued only when ALL jobs with run_group = this value are finished.';
COMMENT ON COLUMN jorb.waitfor_job IS 'Becomes queued only when the job with this id is finished.';

-- the poll/claim path
CREATE INDEX jorb_claim_idx ON jorb (queue, prio, run_after)
    WHERE state = 'queued';
-- rate limiting counts recent admissions per queue
CREATE INDEX jorb_claimed_at_idx ON jorb (queue, claimed_at)
    WHERE claimed_at IS NOT NULL;
-- duration/throughput reporting
CREATE INDEX jorb_started_idx ON jorb (queue, started)
    WHERE started IS NOT NULL;
-- reaper scans
CREATE INDEX jorb_inflight_idx ON jorb (state, updated)
    WHERE state IN ('claimed', 'running');
-- retention: the sweep asks "which terminal jobs aged out?" every cycle, and
-- once it has caught up the honest answer is usually "none". Without this it
-- reads the whole terminal backlog to say so -- measured at 300k rows that is
-- already a full scan, and a busy install keeps orders of magnitude more.
-- Indexed on the expression the sweep actually filters by.
CREATE INDEX jorb_retention_idx ON jorb (COALESCE(finished, updated))
    WHERE state IN ('finished', 'crashed', 'cancelled');
-- reporting windows. Deliberately on `created` and NOT on `updated`:
-- `updated` is rewritten by every state change, so indexing it would add an
-- index write to each of the ~4 updates per job AND block HOT updates on the
-- hottest table in the system -- paying in permanent bloat for a read that
-- happens on a scrape interval. `created` is written once.
CREATE INDEX jorb_created_idx ON jorb (created);
CREATE INDEX jorb_timeout_idx ON jorb (timeout_at)
    WHERE state = 'running' AND timeout_at IS NOT NULL;
-- dependency wakeups
CREATE INDEX jorb_waitfor_job_idx   ON jorb (waitfor_job)   WHERE state = 'waiting';
CREATE INDEX jorb_waitfor_group_idx ON jorb (waitfor_group) WHERE state = 'waiting';
CREATE INDEX jorb_run_group_idx     ON jorb (run_group);
CREATE INDEX jorb_uid_idx           ON jorb (uid);
CREATE INDEX jorb_dag_idx           ON jorb (dag_id) WHERE dag_id IS NOT NULL;
-- idempotent enqueue
CREATE UNIQUE INDEX jorb_deadline_idx ON jorb (deadline_key, queue)
    WHERE state = 'queued' AND deadline_key IS NOT NULL;

-- ----------------------------------------------------------------------------
-- Autovacuum, tuned for this table's write pattern rather than left at the
-- server defaults. A job costs ~4 row versions (insert, claim, run, terminal),
-- so a busy install produces dead tuples in the millions per hour. The default
-- scale factor of 0.2 means "wait until 20% of the table is garbage", which on
-- a large jorb is both far too late and then far too much work at once; the
-- claim index bloats in the meantime.
--
-- fillfactor leaves room on each page for an updated row version to live
-- beside its original, which is what allows a HOT update -- an update that
-- does not have to touch every index. That is why `updated` is not indexed.
ALTER TABLE jorb SET (
    autovacuum_vacuum_scale_factor  = 0.02,
    autovacuum_vacuum_threshold     = 1000,
    autovacuum_analyze_scale_factor = 0.02,
    autovacuum_vacuum_cost_limit    = 2000,
    fillfactor                      = 85
);

-- ============================================================================
-- Queue control plane (live-tunable; absent row = defaults)
-- ============================================================================
CREATE TABLE jorb_queue (
    name                TEXT PRIMARY KEY,
    paused              BOOLEAN     NOT NULL DEFAULT FALSE,
    max_concurrency     INTEGER,              -- NULL = unlimited (claimed+running cap)
    rate_limit          INTEGER,              -- max starts per rate_period; NULL = unlimited
    rate_period_seconds DOUBLE PRECISION NOT NULL DEFAULT 60,
    created             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated             TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE jorb_queue IS 'Per-queue controls enforced by claim_jorb(); rows are optional (missing queue = unpaused, unlimited).';

-- ============================================================================
-- The claim path
-- ============================================================================
-- Claiming lives in the database, not in the worker, so that the queue's
-- controls are enforced for EVERY claimer rather than only for clients that
-- remember to enforce them.
--
-- Why the advisory lock: under READ COMMITTED a statement sees the snapshot
-- taken when it began, so two simultaneous claims cannot see each other's
-- uncommitted rows and a cap of 1 would admit both. Serializing claims for a
-- controlled queue fixes that -- and because PL/pgSQL takes a new snapshot per
-- statement, the counts below run AFTER the lock and therefore see every claim
-- that has already committed. Uncontrolled queues (the common case) never take
-- the lock and keep the lock-free fast path.
CREATE FUNCTION claim_jorb(
    p_queue        TEXT,
    p_capabilities TEXT[],
    p_max_prio     INTEGER,
    p_worker_pid   INTEGER,
    p_worker_host  TEXT,
    p_worker_id    BIGINT
) RETURNS SETOF jorb
LANGUAGE plpgsql AS $$
DECLARE
    q jorb_queue%ROWTYPE;
BEGIN
    SELECT * INTO q FROM jorb_queue WHERE name = p_queue;

    IF COALESCE(q.paused, FALSE) THEN
        RETURN;
    END IF;

    IF q.max_concurrency IS NOT NULL OR q.rate_limit IS NOT NULL THEN
        -- Non-blocking on purpose: a claimer that cannot take the lock right
        -- now reports nothing claimable and polls again, so a claim held open
        -- by a slow or stuck transaction can never freeze the whole queue.
        IF NOT pg_try_advisory_xact_lock(
                   hashtext('pyjobby.claim:' || p_queue)) THEN
            RETURN;
        END IF;

        IF q.max_concurrency IS NOT NULL AND q.max_concurrency <= (
               SELECT count(*) FROM jorb
               WHERE queue = p_queue AND state IN ('claimed', 'running')) THEN
            RETURN;
        END IF;

        IF q.rate_limit IS NOT NULL AND q.rate_limit <= (
               SELECT count(*) FROM jorb
               WHERE queue = p_queue
                 AND claimed_at > now()
                     - make_interval(secs => q.rate_period_seconds)) THEN
            RETURN;
        END IF;
    END IF;

    RETURN QUERY
    UPDATE jorb
       SET state      = 'claimed',
           worker_pid = p_worker_pid,
           worker_host= p_worker_host,
           claimed_by = p_worker_id,
           claimed_at = now(),
           run_count  = run_count + 1,
           run_epoch  = run_epoch + 1,
           updated    = now()
     WHERE id = (
           SELECT j.id FROM jorb j
            WHERE j.queue = p_queue
              AND (j.capability = ANY(p_capabilities) OR j.capability IS NULL)
              AND j.prio <= p_max_prio
              AND j.run_after <= now()
              AND j.state = 'queued'
            ORDER BY j.prio, j.run_after
              FOR UPDATE OF j SKIP LOCKED
            LIMIT 1)
    RETURNING *;
END;
$$;

COMMENT ON FUNCTION claim_jorb IS 'Atomically admit at most one queued job for a worker, enforcing the queue pause/concurrency/rate controls. Returns zero rows when nothing is claimable.';

-- ============================================================================
-- Worker registry (exact liveness; replaces pid/grace guessing)
-- ============================================================================
CREATE TABLE jorb_worker (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host         TEXT        NOT NULL,
    pid          INTEGER     NOT NULL,
    queue        TEXT        NOT NULL,
    capabilities TEXT[]      NOT NULL DEFAULT '{}',
    version      TEXT,
    started      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen    TIMESTAMPTZ NOT NULL DEFAULT now(),
    shutdown_at  TIMESTAMPTZ           -- set on graceful exit
);

CREATE INDEX jorb_worker_live_idx ON jorb_worker (last_seen) WHERE shutdown_at IS NULL;

COMMENT ON TABLE jorb_worker IS 'One row per worker process; heartbeats update last_seen. A live worker = shutdown_at IS NULL and recent last_seen.';

-- ============================================================================
-- DXE: step checkpoints (durable execution)
-- ============================================================================
CREATE TABLE jorb_step (
    job_id    BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    step_seq  INTEGER     NOT NULL,
    name      TEXT        NOT NULL,
    output    JSONB,
    error     TEXT,                    -- recorded exception; replay re-raises
    run_epoch INTEGER     NOT NULL,    -- which attempt produced this checkpoint
    started   TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished  TIMESTAMPTZ,
    PRIMARY KEY (job_id, step_seq)
);

COMMENT ON TABLE jorb_step IS 'DXE checkpoints: a completed step is never re-executed on retry/resume; a name mismatch at a step_seq means nondeterministic job code.';

-- ============================================================================
-- DXE: key/value events (job publishes, anyone reads/awaits)
-- ============================================================================
CREATE TABLE jorb_event (
    job_id  BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    key     TEXT        NOT NULL,
    value   JSONB       NOT NULL,
    updated TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (job_id, key)
);

-- ============================================================================
-- DXE: durable job-to-job messages
-- ============================================================================
CREATE TABLE jorb_mailbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dest_job_id BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    topic       TEXT,
    message     JSONB       NOT NULL,
    created     TIMESTAMPTZ NOT NULL DEFAULT now(),
    consumed_at TIMESTAMPTZ
);

CREATE INDEX jorb_mailbox_pending_idx ON jorb_mailbox (dest_job_id, topic, id)
    WHERE consumed_at IS NULL;

-- ============================================================================
-- Transition history (first-class audit; retries keep one job id)
-- ============================================================================
CREATE TABLE jorb_history (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- cascades like every other child of jorb: history is the biggest of
    -- them, so without the key retention would free the small tables and
    -- leave the largest one growing forever
    job_id  BIGINT      NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    event   TEXT        NOT NULL,  -- enqueued|claimed|started|finished|retrying|crashed|cancelled|timeout|requeued|recovered
    detail  JSONB       NOT NULL DEFAULT '{}'
);

CREATE INDEX jorb_history_job_idx ON jorb_history (job_id, id);

-- Append-only until retention deletes in bulk, so it needs a low scale factor
-- to clean up promptly after a sweep, but no fillfactor headroom.
ALTER TABLE jorb_history SET (
    autovacuum_vacuum_scale_factor = 0.05,
    autovacuum_vacuum_threshold    = 5000,
    autovacuum_vacuum_cost_limit   = 2000
);


COMMENT ON TABLE jorb_history IS 'Every state transition with worker/epoch/error detail; the per-attempt audit trail (jobs keep one row in jorb for life).';

-- ============================================================================
-- Recurring schedules (cron) + execution log
-- ============================================================================
CREATE TABLE jorb_schedule (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      TEXT    NOT NULL UNIQUE,
    description               TEXT,
    job_class                 TEXT    NOT NULL,
    kwargs                    JSONB   NOT NULL DEFAULT '{}',
    queue                     TEXT    NOT NULL DEFAULT 'default',
    prio                      INTEGER NOT NULL DEFAULT 100,
    capability                TEXT,
    cron_expr                 TEXT    NOT NULL,
    timezone                  TEXT    NOT NULL DEFAULT 'UTC',
    enabled                   BOOLEAN NOT NULL DEFAULT TRUE,
    max_concurrent_jobs       INTEGER NOT NULL DEFAULT 1,
    jitter_seconds            INTEGER NOT NULL DEFAULT 0,
    backpressure_threshold    INTEGER          DEFAULT 1000,
    circuit_breaker_threshold INTEGER NOT NULL DEFAULT 5,
    consecutive_failures      INTEGER NOT NULL DEFAULT 0,
    next_run                  TIMESTAMPTZ NOT NULL,
    last_run                  TIMESTAMPTZ,
    last_success              TIMESTAMPTZ,
    last_failure              TIMESTAMPTZ,
    run_count                 BIGINT  NOT NULL DEFAULT 0,
    success_count             BIGINT  NOT NULL DEFAULT 0,
    failure_count             BIGINT  NOT NULL DEFAULT 0,
    skip_count                BIGINT  NOT NULL DEFAULT 0,
    created                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by                TEXT
);

CREATE INDEX jorb_schedule_due_idx ON jorb_schedule (next_run) WHERE enabled;

CREATE TABLE jorb_schedule_log (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id            BIGINT NOT NULL REFERENCES jorb_schedule (id) ON DELETE CASCADE,
    schedule_name          TEXT   NOT NULL,
    scheduled_time         TIMESTAMPTZ NOT NULL,
    actual_time            TIMESTAMPTZ NOT NULL DEFAULT now(),
    result                 TEXT   NOT NULL,  -- success|failure|skipped
    skip_reason            TEXT,
    job_id                 BIGINT,
    error_message          TEXT,
    duration_ms            INTEGER,
    queue_depth_at_run     INTEGER,
    concurrent_jobs_at_run INTEGER,
    jitter_applied_seconds INTEGER
);

CREATE INDEX jorb_schedule_log_idx ON jorb_schedule_log (schedule_id, id);

-- ============================================================================
-- DAG orchestration
-- ============================================================================
CREATE TABLE jorb_dag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT,
    created     TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed   TIMESTAMPTZ,
    metadata    JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE jorb_dependencies (
    job_id     BIGINT NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    depends_on BIGINT NOT NULL REFERENCES jorb (id) ON DELETE CASCADE,
    PRIMARY KEY (job_id, depends_on)
);

-- The primary key leads with job_id, so THAT cascade is indexed; depends_on
-- is a second foreign key to the same table and Postgres indexes neither
-- automatically. Without this, deleting a job sequentially scans this table
-- looking for edges that point at it -- once per deleted job, which is
-- exactly what retention does in bulk.
CREATE INDEX jorb_dependencies_depends_on_idx ON jorb_dependencies (depends_on);

ALTER TABLE jorb ADD CONSTRAINT jorb_dag_fk
    FOREIGN KEY (dag_id) REFERENCES jorb_dag (id) ON DELETE SET NULL;

CREATE VIEW jorb_dag_status AS
    SELECT d.id AS dag_id,
           d.name,
           d.created,
           d.completed,
           count(j.id)                                            AS total_jobs,
           count(j.id) FILTER (WHERE j.state = 'finished')        AS finished_jobs,
           count(j.id) FILTER (WHERE j.state = 'crashed')         AS crashed_jobs,
           count(j.id) FILTER (WHERE j.state = 'cancelled')       AS cancelled_jobs,
           count(j.id) FILTER (WHERE j.state IN ('queued','claimed','running','waiting')) AS pending_jobs
    FROM jorb_dag d
    LEFT JOIN jorb j ON j.dag_id = d.id
    GROUP BY d.id;

CREATE VIEW jorb_dag_timeline AS
    SELECT j.dag_id,
           j.id AS job_id,
           j.job_class,
           j.state,
           j.started,
           j.finished,
           EXTRACT(EPOCH FROM (j.finished - j.started)) AS duration_seconds
    FROM jorb j
    WHERE j.dag_id IS NOT NULL;

-- ============================================================================
-- Notify channels (reliable — every event, no sampling)
-- ============================================================================

-- Wake idle workers the moment a job becomes claimable in their queue.
CREATE FUNCTION notify_jorb_enqueued() RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('jorb_enqueued', NEW.queue);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER jorb_enqueued_notify
    AFTER INSERT OR UPDATE OF state ON jorb
    FOR EACH ROW WHEN (NEW.state = 'queued')
    EXECUTE FUNCTION notify_jorb_enqueued();

-- Tell waiters a job reached a terminal state (client wait_for_result).
CREATE FUNCTION notify_jorb_done() RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('jorb_done',
        json_build_object('id', NEW.id, 'state', NEW.state)::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER jorb_done_notify
    AFTER UPDATE OF state ON jorb
    FOR EACH ROW WHEN (NEW.state IN ('finished', 'crashed', 'cancelled'))
    EXECUTE FUNCTION notify_jorb_done();

-- Tell the executing worker a running job should stop.
CREATE FUNCTION notify_jorb_cancel() RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('jorb_cancel', NEW.id::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER jorb_cancel_notify
    AFTER UPDATE OF cancel_requested ON jorb
    FOR EACH ROW WHEN (NEW.cancel_requested AND NEW.state = 'running')
    EXECUTE FUNCTION notify_jorb_cancel();

-- Wake event waiters (get_event) and mailbox receivers (recv).
CREATE FUNCTION notify_jorb_event() RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('jorb_event',
        json_build_object('job_id', NEW.job_id, 'key', NEW.key)::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER jorb_event_notify
    AFTER INSERT OR UPDATE ON jorb_event
    FOR EACH ROW EXECUTE FUNCTION notify_jorb_event();

CREATE FUNCTION notify_jorb_mailbox() RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('jorb_mailbox',
        json_build_object('dest', NEW.dest_job_id, 'topic', NEW.topic)::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER jorb_mailbox_notify
    AFTER INSERT ON jorb_mailbox
    FOR EACH ROW EXECUTE FUNCTION notify_jorb_mailbox();

-- Dashboard state-change feed (reliable now; consumers decide what to drop).
CREATE FUNCTION notify_job_state_change() RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('job_state_change', json_build_object(
        'id', NEW.id,
        'queue', NEW.queue,
        'job_class', NEW.job_class,
        'old_state', OLD.state,
        'new_state', NEW.state,
        'error_count', NEW.error_count
    )::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER job_state_change_notify
    AFTER UPDATE OF state ON jorb
    FOR EACH ROW WHEN (OLD.state IS DISTINCT FROM NEW.state)
    EXECUTE FUNCTION notify_job_state_change();

-- ============================================================================
-- DAG completion: stamped when a DAG's last job reaches a terminal state
-- ============================================================================
-- Recorded by trigger (like history) so every writer — worker, monitor,
-- admin API — keeps jorb_dag.completed truthful without having to know
-- about DAGs.
CREATE FUNCTION complete_jorb_dag() RETURNS trigger AS $$
BEGIN
    IF NEW.dag_id IS NOT NULL THEN
        UPDATE jorb_dag d
        SET completed = now()
        WHERE d.id = NEW.dag_id
          AND d.completed IS NULL
          AND NOT EXISTS (
              SELECT 1 FROM jorb j
              WHERE j.dag_id = NEW.dag_id
                AND j.state NOT IN ('finished', 'crashed', 'cancelled')
          );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER jorb_dag_complete
    AFTER UPDATE OF state ON jorb
    FOR EACH ROW
    WHEN (NEW.state IN ('finished', 'crashed', 'cancelled')
          AND NEW.dag_id IS NOT NULL)
    EXECUTE FUNCTION complete_jorb_dag();

-- ============================================================================
-- History recording: one trigger, every writer covered
-- ============================================================================
-- The worker, monitor, scheduler, admin API, and websocket server all mutate
-- jorb; recording transitions here means none of them can forget to.
CREATE FUNCTION record_jorb_history() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO jorb_history (job_id, event, detail)
        VALUES (NEW.id, 'enqueued', jsonb_build_object(
            'queue', NEW.queue, 'job_class', NEW.job_class,
            'state', NEW.state, 'prio', NEW.prio));
    ELSIF OLD.state IS DISTINCT FROM NEW.state THEN
        INSERT INTO jorb_history (job_id, event, detail)
        VALUES (NEW.id, NEW.state::text, jsonb_build_object(
            'from', OLD.state,
            'run_epoch', NEW.run_epoch,
            'run_count', NEW.run_count,
            'error_count', NEW.error_count,
            'worker_host', NEW.worker_host,
            'worker_pid', NEW.worker_pid,
            'error', CASE WHEN NEW.state IN ('queued','crashed')
                          THEN NEW.error_message END));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER jorb_history_record
    AFTER INSERT OR UPDATE OF state ON jorb
    FOR EACH ROW EXECUTE FUNCTION record_jorb_history();

-- Dashboard schedule execution feed.
CREATE FUNCTION notify_schedule_executed() RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('schedule_executed', json_build_object(
        'schedule_id', NEW.schedule_id,
        'schedule_name', NEW.schedule_name,
        'result', NEW.result,
        'job_id', NEW.job_id
    )::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER schedule_executed_notify
    AFTER INSERT ON jorb_schedule_log
    FOR EACH ROW EXECUTE FUNCTION notify_schedule_executed();
