"""Executable proof for every example in ``docs/writing-jobs.md``.

The job classes below are the guide's examples, verbatim: the document is
written from this file, not beside it. Each test enqueues one of them and
drives a REAL worker (the ``live_worker`` fixture), so an API change breaks
the guide here instead of leaving it quietly wrong.

The workers run in this process, which is why a plain module-level list is
enough to observe "did that step really execute again?" — the job code and
the assertion share one interpreter. ``guide_payment`` is the little
application table the ``transaction()`` example writes to; it is created on
demand here and belongs to this file, not to the schema.
"""

from __future__ import annotations

import asyncio
import time
from typing import Any

import pytest
import pytest_asyncio

from pyjobby import Job, job

from .conftest import wait_for_job_state

pytestmark = pytest.mark.asyncio

# Executions the guide's examples want to be able to count. The worker runs
# in this process, so appending here is the cheapest possible stand-in for
# "the remote system was called".
FETCHES: list[int] = []
CHARGE_LOOKUPS: list[int] = []


GUIDE_PAYMENT_DDL = """CREATE TABLE IF NOT EXISTS guide_payment (
        id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT      NOT NULL,
        cents    INTEGER     NOT NULL,
        at       TIMESTAMPTZ NOT NULL DEFAULT now()
    )"""


@pytest_asyncio.fixture
async def payments_table(db_pool):
    """The application table the ``transaction()`` example writes to."""
    await db_pool.execute(GUIDE_PAYMENT_DDL)
    await db_pool.execute("DELETE FROM guide_payment WHERE at < now() - interval '1 h'")
    return "guide_payment"


# ===========================================================================
# Defining a job
# ===========================================================================


class Greet(Job):
    """A synchronous job: arguments in, JSON-serializable result out."""

    def task(self, name: str, greeting: str = "hello") -> dict[str, str]:
        return {"message": f"{greeting}, {name}!"}


class StreamBatches(Job):
    """An async generator: the worker stores the list of everything yielded."""

    async def task(self, count: int = 3) -> Any:
        for i in range(count):
            yield {"batch": i}


async def test_a_sync_job_returns_its_result(client, live_worker, unique_queue):
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.Greet", queue=unique_queue, name="ada"
    )

    row = await wait_for_job_state(client.pool, job_id, ("finished",))
    assert row["result"] == {"message": "hello, ada!"}


async def test_an_async_generator_stores_every_yield(client, live_worker, unique_queue):
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.StreamBatches", queue=unique_queue, count=3
    )

    row = await wait_for_job_state(client.pool, job_id, ("finished",))
    assert row["result"] == [{"batch": 0}, {"batch": 1}, {"batch": 2}]


# ===========================================================================
# step(): expensive work that must not be repeated
# ===========================================================================


class ImportOrder(Job):
    """Two steps; the second fails once, and the first never runs twice."""

    async def task(self, order_id: int) -> dict[str, Any]:
        order = await self.step("fetch", self.fetch_order, order_id)
        await self.step("charge", self.charge, order)
        return {"imported": order["id"]}

    def fetch_order(self, order_id: int) -> dict[str, Any]:
        FETCHES.append(order_id)  # the expensive call you do not want repeated
        return {"id": order_id, "cents": 1999}

    def charge(self, order: dict[str, Any]) -> dict[str, Any]:
        if self.job["error_count"] == 0:  # fail once, to show the retry
            raise RuntimeError("payment gateway timed out")
        return {"charged": order["cents"]}


async def test_a_completed_step_is_not_repeated_on_retry(
    client, live_worker, unique_queue
):
    FETCHES.clear()
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.ImportOrder",
        queue=unique_queue,
        max_retries=3,
        initial_retry_delay=0,
        order_id=42,
    )

    row = await wait_for_job_state(client.pool, job_id, ("finished",))
    assert row["result"] == {"imported": 42}
    assert row["error_count"] == 1  # one failed attempt
    assert FETCHES == [42]  # ...and the fetch still ran exactly once

    steps = await client.pool.fetch(
        "SELECT step_seq, name, output FROM jorb_step WHERE job_id=$1 ORDER BY step_seq",
        job_id,
    )
    assert [s["name"] for s in steps] == ["fetch", "charge"]


# ===========================================================================
# transaction(): exactly-once for writes to this database
# ===========================================================================


class RecordPayment(Job):
    """The write and its checkpoint are one commit, so neither can be lost."""

    async def task(self, order_id: int, cents: int) -> dict[str, Any]:
        return await self.transaction("record", self.record, order_id, cents)

    async def record(self, conn: Any, order_id: int, cents: int) -> dict[str, Any]:
        await conn.execute(
            "INSERT INTO guide_payment (order_id, cents) VALUES ($1, $2)",
            order_id,
            cents,
        )
        if self.job["error_count"] == 0:
            # a crash here rolls the INSERT back with the checkpoint
            raise RuntimeError("crashed after the write, before the commit")
        return {"order": order_id, "cents": cents}


async def test_a_transaction_writes_exactly_once(
    client, live_worker, unique_queue, payments_table
):
    await live_worker()

    order_id = int(time.time() * 1000) % 1_000_000_000
    job_id = await client.enqueue(
        "tests.test_writing_jobs.RecordPayment",
        queue=unique_queue,
        max_retries=3,
        initial_retry_delay=0,
        order_id=order_id,
        cents=1999,
    )

    row = await wait_for_job_state(client.pool, job_id, ("finished",))
    assert row["result"] == {"order": order_id, "cents": 1999}
    assert row["error_count"] == 1  # the first attempt wrote, then raised

    # the rolled-back write left nothing: exactly one row, not two
    written = await client.pool.fetch(
        "SELECT cents FROM guide_payment WHERE order_id = $1", order_id
    )
    assert [r["cents"] for r in written] == [1999]


# ===========================================================================
# sleep(): waiting without holding a worker
# ===========================================================================


class PollShipment(Job):
    """Publishes where it is, sleeps durably, then finishes."""

    async def task(self, order_id: int) -> dict[str, Any]:
        await self.set_event("stage", {"at": "awaiting-carrier"})
        await self.sleep(1)
        return {"order": order_id, "stage": "delivered"}


async def test_a_durable_sleep_holds_no_worker(client, live_worker, unique_queue):
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.PollShipment", queue=unique_queue, order_id=7
    )

    # while it sleeps the job is back in the queue with a future run_after —
    # it occupies no worker and no connection
    for _ in range(50):
        row = await client.pool.fetchrow(
            "SELECT state, run_after > now() AS future FROM jorb WHERE id=$1", job_id
        )
        if row["state"] == "queued" and row["future"]:
            break
        await asyncio.sleep(0.1)
    assert row["state"] == "queued" and row["future"], dict(row)
    assert await client.get_event(job_id, "stage", timeout=5) == {
        "at": "awaiting-carrier"
    }

    row = await wait_for_job_state(client.pool, job_id, ("finished",), timeout=15)
    assert row["result"] == {"order": 7, "stage": "delivered"}


# ===========================================================================
# set_event() / send() / recv(): coordination
# ===========================================================================


class WaitForApproval(Job):
    """Announces itself, then blocks on its mailbox until someone decides."""

    async def task(self, order_id: int, timeout: float = 20) -> dict[str, Any]:
        await self.set_event("awaiting", {"order": order_id})
        decision = await self.recv(topic="approval", timeout=timeout)
        return {"approved": bool(decision and decision.get("ok"))}


class Approve(Job):
    """Delivers the decision to another job's mailbox."""

    async def task(self, dest: int) -> str:
        await self.send(dest, {"ok": True}, topic="approval")
        return "sent"


async def test_one_job_unblocks_another(client, live_worker, unique_queue):
    await live_worker()
    await live_worker()  # second worker: the approver must not queue behind the waiter

    waiter = await client.enqueue(
        "tests.test_writing_jobs.WaitForApproval", queue=unique_queue, order_id=99
    )
    assert await client.get_event(waiter, "awaiting", timeout=10) == {"order": 99}

    approver = await client.enqueue(
        "tests.test_writing_jobs.Approve", queue=unique_queue, dest=waiter
    )
    await wait_for_job_state(client.pool, approver, ("finished",))

    row = await wait_for_job_state(client.pool, waiter, ("finished",), timeout=25)
    assert row["result"] == {"approved": True}


async def test_an_operator_can_deliver_the_same_message(
    client, live_worker, unique_queue
):
    """`recv()` does not care who sent it: the client can too."""
    await live_worker()

    waiter = await client.enqueue(
        "tests.test_writing_jobs.WaitForApproval", queue=unique_queue, order_id=100
    )
    await client.get_event(waiter, "awaiting", timeout=10)
    await client.send_message(waiter, {"ok": True}, topic="approval")

    row = await wait_for_job_state(client.pool, waiter, ("finished",), timeout=25)
    assert row["result"] == {"approved": True}


# ===========================================================================
# self.cancelled: cooperative cancellation in a long synchronous loop
# ===========================================================================


class ReindexEverything(Job):
    """A long synchronous loop that asks whether an operator cancelled it."""

    def task(self, batches: int = 600) -> dict[str, int]:
        done = 0
        for _ in range(batches):
            if self.cancelled:  # operator asked us to stop
                break
            time.sleep(0.05)  # one batch of real work
            done += 1
        return {"batches": done}


async def test_a_sync_loop_can_stop_itself_when_cancelled(
    client, live_worker, unique_queue
):
    worker = await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.ReindexEverything", queue=unique_queue, batches=600
    )
    await wait_for_job_state(client.pool, job_id, ("running",))

    assert await client.cancel_job(job_id) == {
        "job_id": job_id,
        "status": "cancel_requested",
    }
    row = await wait_for_job_state(client.pool, job_id, ("cancelled",))
    assert row["state"] == "cancelled"

    # the point of polling self.cancelled: the thread ENDS. Nothing can
    # interrupt a synchronous loop, so a loop that never looked would hold a
    # slot in this worker's pool for the full 30s.
    for _ in range(40):
        if worker._live_job_threads() == 0:
            break
        await asyncio.sleep(0.1)
    assert worker._live_job_threads() == 0


# ===========================================================================
# Determinism: the step sequence must be the same on every attempt
# ===========================================================================


class BranchOutsideStep(Job):
    """WRONG: the branch changes which step is number 1."""

    async def task(self) -> dict[str, Any]:
        if self.job["error_count"] == 0:
            await self.step("probe", lambda: {"seen": True})
            raise RuntimeError("something transient")
        return await self.step("finish", lambda: {"ok": True})


class BranchInsideStep(Job):
    """RIGHT: the choice is checkpointed, so every attempt makes it again."""

    async def task(self, order_id: int) -> dict[str, Any]:
        charged = await self.step("was-charged", self.was_charged, order_id)
        if charged:
            await self.step("refund", self.refund, order_id)
        return {"refunded": charged}

    def was_charged(self, order_id: int) -> bool:
        CHARGE_LOOKUPS.append(order_id)  # a fact that could change under us
        return True

    def refund(self, order_id: int) -> dict[str, Any]:
        if self.job["error_count"] == 0:
            raise RuntimeError("refund API unavailable")
        return {"refunded": order_id}


async def test_changing_the_step_sequence_is_refused(client, live_worker, unique_queue):
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.BranchOutsideStep",
        queue=unique_queue,
        max_retries=3,
        initial_retry_delay=0,
    )

    row = await wait_for_job_state(client.pool, job_id, ("crashed",), timeout=20)
    assert (
        "step 1 was 'probe' on a previous attempt but is 'finish' now"
        in (row["error_message"])
    )
    assert "deterministic outside steps" in row["error_message"]


async def test_checkpointing_the_choice_makes_replay_stable(
    client, live_worker, unique_queue
):
    CHARGE_LOOKUPS.clear()
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.BranchInsideStep",
        queue=unique_queue,
        max_retries=3,
        initial_retry_delay=0,
        order_id=5,
    )

    row = await wait_for_job_state(client.pool, job_id, ("finished",), timeout=20)
    assert row["result"] == {"refunded": True}
    assert row["error_count"] == 1
    # the fact was read once and replayed thereafter, so the second attempt
    # took the same branch even if the world had changed
    assert CHARGE_LOOKUPS == [5]


# ===========================================================================
# Timeouts
# ===========================================================================


class RenderReport(Job):
    """A per-step budget: the step that hangs is the one that is blamed."""

    step_timeout = 5  # default budget for every step in this job

    async def task(self) -> dict[str, Any]:
        rows = await self.step("gather", self.gather)
        return await self.step("render", self.render, rows, timeout=0.2)

    async def gather(self) -> list[int]:
        return [1, 2, 3]

    async def render(self, rows: list[int]) -> dict[str, Any]:
        await asyncio.sleep(5)  # hangs, far past this step's 0.2s
        return {"rows": len(rows)}


class Impatient(Job):
    """A job-level ceiling: this job may never run longer than a second."""

    timeout = 1

    async def task(self) -> str:
        await asyncio.sleep(30)
        return "never"


async def test_a_blown_step_budget_is_recorded_against_that_step(
    client, live_worker, unique_queue
):
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.RenderReport",
        queue=unique_queue,
        max_retries=1,  # no retry: go straight to the dead-letter state
        initial_retry_delay=0,
    )

    row = await wait_for_job_state(client.pool, job_id, ("crashed",), timeout=20)
    assert "step 'render' exceeded its 0.2s timeout" in row["error_message"]

    steps = await client.pool.fetch(
        """SELECT step_seq, name, output, error FROM jorb_step
            WHERE job_id=$1 ORDER BY step_seq""",
        job_id,
    )
    assert steps[0]["name"] == "gather"
    assert steps[0]["output"] == [1, 2, 3]  # the completed prefix stands
    assert steps[1]["name"] == "render"
    assert steps[1]["error"].startswith("StepTimeoutError:")


async def test_the_job_timeout_is_the_ceiling(client, live_worker, unique_queue):
    """The class attribute bounds the job; a timeout is an ordinary failure."""
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.Impatient",
        queue=unique_queue,
        max_retries=1,  # one attempt, so the timeout is terminal
        initial_retry_delay=0,
    )

    row = await wait_for_job_state(client.pool, job_id, ("crashed",), timeout=20)
    assert row["error_message"] == "Job timed out after 1s"


class Unbounded(Job):
    """No deadline of its own: whatever bounds it comes from outside.

    Not one of the guide's snippets — it is what proves the guide's claim
    that the worker's --default-timeout is a deadline like the other two,
    which needs a job class that declines to name one.
    """

    async def task(self) -> str:
        await asyncio.sleep(30)
        return "never"


# ---------------------------------------------------------------------------
# `on_timeout` is a policy about the job's deadline, wherever that deadline
# came from. There are exactly three sources -- `timeout_seconds=` at
# enqueue, the class's `timeout` attribute, the worker's --default-timeout --
# and the policy has to mean the same thing for all three, because the caller
# writing `on_timeout='fail'` cannot see which one will bind.
#
# `fail` is terminal on the first overrun (error_count == 1 with retries left
# on the table); `retry` spends the budget and dead-letters at the end of it
# (error_count == max_retries). Driven by a real worker, since the whole
# question is what the worker does with the value the client stored.
# ---------------------------------------------------------------------------


async def test_on_timeout_fail_skips_the_retries(client, live_worker, unique_queue):
    """Deadline from `timeout_seconds=` at enqueue."""
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.Impatient",
        queue=unique_queue,
        timeout_seconds=1,  # this enqueue's deadline, overriding the class
        on_timeout="fail",  # ...and do not spend retries on it
        max_retries=10,
    )

    row = await wait_for_job_state(client.pool, job_id, ("crashed",), timeout=20)
    assert row["error_message"] == "Job timed out after 1s"
    assert row["error_count"] == 1  # terminal on the first overrun


async def test_on_timeout_fail_applies_to_the_class_deadline(
    client, live_worker, unique_queue
):
    """Deadline from the class's `timeout` attribute.

    Nothing about this enqueue mentions a number, and that is the point: the
    caller asked for "a timeout must not be retried" and the job class is
    what says when a timeout is. Recording the policy only alongside
    `timeout_seconds=` dropped it here, and the job retried -- the opposite
    of what was asked for, silently.
    """
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.Impatient",  # timeout = 1
        queue=unique_queue,
        on_timeout="fail",
        max_retries=10,
    )

    row = await wait_for_job_state(client.pool, job_id, ("crashed",), timeout=20)
    assert row["error_message"] == "Job timed out after 1s"
    assert row["error_count"] == 1


async def test_on_timeout_fail_applies_to_the_worker_default_deadline(
    client, live_worker, unique_queue
):
    """Deadline from the worker's --default-timeout: neither the enqueue nor
    the class named one, and the operator's fleet-wide ceiling bound it."""
    await live_worker(default_timeout=1)

    job_id = await client.enqueue(
        "tests.test_writing_jobs.Unbounded",  # timeout is None
        queue=unique_queue,
        on_timeout="fail",
        max_retries=10,
    )

    row = await wait_for_job_state(client.pool, job_id, ("crashed",), timeout=20)
    assert row["error_message"] == "Job timed out after 1s"
    assert row["error_count"] == 1


@pytest.mark.parametrize(
    "job_class,options,worker_options",
    [
        ("Impatient", {"timeout_seconds": 1}, {}),
        ("Impatient", {}, {}),
        ("Unbounded", {}, {"default_timeout": 1}),
    ],
    ids=["enqueue_argument", "class_attribute", "worker_default"],
)
async def test_on_timeout_retry_spends_the_budget_from_every_source(
    client, live_worker, unique_queue, job_class, options, worker_options
):
    """The mirror: 'retry' (the default) still retries, from all three."""
    await live_worker(**worker_options)

    job_id = await client.enqueue(
        f"tests.test_writing_jobs.{job_class}",
        queue=unique_queue,
        on_timeout="retry",
        max_retries=2,  # one retry, then the dead-letter state
        initial_retry_delay=0,
        **options,
    )

    row = await wait_for_job_state(client.pool, job_id, ("crashed",), timeout=30)
    assert row["error_message"] == "Job timed out after 1s"
    assert row["error_count"] == 2  # the budget was spent, not skipped


async def test_an_unknown_on_timeout_is_refused_at_enqueue(client, unique_queue):
    """The worker asks `== 'retry'` and treats everything else as terminal,
    so a typo would dead-letter jobs on their first overrun. The client can
    see that much without knowing where the deadline comes from."""
    with pytest.raises(ValueError, match="on_timeout must be one of"):
        await client.enqueue(
            "tests.test_writing_jobs.Impatient",
            queue=unique_queue,
            on_timeout="ignore",
        )


# ===========================================================================
# Retries and the dead-letter state
# ===========================================================================


class AlwaysFails(Job):
    """Exhausts its retries and ends `crashed` — the dead-letter state."""

    def task(self) -> None:
        raise ValueError("nothing here works")


async def test_retries_are_exhausted_into_crashed(client, live_worker, unique_queue):
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.AlwaysFails",
        queue=unique_queue,
        max_retries=2,
        retry_strategy="fixed",
        initial_retry_delay=0,
    )

    row = await wait_for_job_state(client.pool, job_id, ("crashed",), timeout=20)
    assert row["error_count"] == 2  # two attempts, then terminal
    assert "nothing here works" in row["error_message"]


# ===========================================================================
# Registration: the typed @job decorator
# ===========================================================================


@job
class ResizeImage(Job):
    """Registered, so it enqueues itself with checked keyword arguments."""

    async def task(self, url: str, width: int = 128) -> dict[str, Any]:
        return {"url": url, "width": width}


async def test_typed_enqueue_runs_and_validates(client, live_worker, unique_queue):
    await live_worker()

    job_id = await ResizeImage.enqueue(
        client, queue=unique_queue, url="s3://bucket/a.png", width=64
    )

    row = await wait_for_job_state(client.pool, job_id, ("finished",))
    assert row["result"] == {"url": "s3://bucket/a.png", "width": 64}

    # a typo never reaches the database
    with pytest.raises(TypeError):
        await ResizeImage.enqueue(client, queue=unique_queue, widht=64)


async def test_job_tags_are_filterable(client, live_worker, unique_queue):
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_writing_jobs.Greet",
        queue=unique_queue,
        tags={"customer": "acme", "batch": 42},
        name="acme",
    )
    await wait_for_job_state(client.pool, job_id, ("finished",))

    found = await client.search_jobs(tags={"customer": "acme", "batch": 42})
    assert job_id in [j["id"] for j in found]
