"""Executable proof for every complete example in ``docs/EXAMPLES.md``.

Same contract as ``tests/test_writing_jobs.py``: the job classes below are
the document's examples verbatim, the document is written FROM this file,
and each one is driven by a REAL worker (the ``live_worker`` fixture) so an
API change breaks the examples here instead of leaving a new user's first
copy-paste quietly broken.

``docs/EXAMPLES.md`` is about composing jobs into an application — pipelines,
fan-out, the transactional outbox, scheduling — where ``writing-jobs.md`` is
about what goes inside one job. The overlap is deliberate but shallow: the
primitives are demonstrated there, applied here.

``example_order`` and ``example_row`` are the little application tables the
``transaction()`` and outbox examples write to. They belong to this file, not
to the schema, and are created on demand.
"""

from __future__ import annotations

import asyncio
import uuid
from typing import Any

import asyncpg
import pytest
import pytest_asyncio

from pyjobby import Job, JobClient, JobFailedError, job
from pyjobby.db import utcnow

from .conftest import wait_for_job_state

pytestmark = pytest.mark.asyncio


# Real executions the examples want to be able to count. The worker runs in
# this process, so a module-level list is the cheapest possible stand-in for
# "the remote system was actually called".
CHARGES: list[str] = []
FETCHES: list[int] = []


APP_TABLES_DDL = (
    """CREATE TABLE IF NOT EXISTS example_order (
        id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ref      TEXT        NOT NULL,
        cents    INTEGER     NOT NULL,
        at       TIMESTAMPTZ NOT NULL DEFAULT now()
    )""",
    """CREATE TABLE IF NOT EXISTS example_row (
        id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        batch    TEXT        NOT NULL,
        sku      TEXT        NOT NULL,
        units    INTEGER     NOT NULL,
        at       TIMESTAMPTZ NOT NULL DEFAULT now()
    )""",
)


@pytest_asyncio.fixture
async def app_tables(db_pool):
    """The application tables the database examples write to."""
    for ddl in APP_TABLES_DDL:
        await db_pool.execute(ddl)
    for table in ("example_order", "example_row"):
        await db_pool.execute(
            f"DELETE FROM {table} WHERE at < now() - interval '1 hour'"  # noqa: S608
        )
    return True


@pytest.fixture
def batch_ref() -> str:
    """A value unique to this test, so its rows are its own."""
    return uuid.uuid4().hex[:12]


# ===========================================================================
# 1. Web application: accept the request, do the work later
# ===========================================================================


class ProcessUpload(Job):
    """Parse an uploaded batch once, then record it exactly once.

    The parse is a ``step()`` because re-parsing on a retry is waste; the
    write is a ``transaction()`` because a retry that wrote twice would
    double the batch.
    """

    async def task(self, batch: str, raw: list[str]) -> dict[str, Any]:
        rows = await self.step("parse", self.parse, raw)
        await self.transaction("store", self.store, batch, rows)
        return {"batch": batch, "rows": len(rows)}

    def parse(self, raw: list[str]) -> list[dict[str, Any]]:
        FETCHES.append(len(raw))  # the expensive work, counted
        return [
            {"sku": sku, "units": int(units)}
            for sku, units in (line.split(",") for line in raw)
        ]

    async def store(
        self, conn: Any, batch: str, rows: list[dict[str, Any]]
    ) -> list[int]:
        written = []
        for row in rows:
            written.append(
                await conn.fetchval(
                    "INSERT INTO example_row (batch, sku, units) "
                    "VALUES ($1, $2, $3) RETURNING id",
                    batch,
                    row["sku"],
                    row["units"],
                )
            )
        if self.job["error_count"] == 0:
            # a crash here rolls the whole INSERT set back with the checkpoint
            raise RuntimeError("crashed before the commit")
        return written


async def test_the_upload_job_parses_once_and_writes_once(
    client, live_worker, unique_queue, app_tables, batch_ref
):
    FETCHES.clear()
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_examples_doc.ProcessUpload",
        queue=unique_queue,
        max_retries=3,
        initial_retry_delay=0,
        batch=batch_ref,
        raw=["a-1,2", "b-2,5"],
    )

    row = await wait_for_job_state(client.pool, job_id, ("finished",), timeout=20)
    assert row["result"] == {"batch": batch_ref, "rows": 2}
    assert row["error_count"] == 1  # the first attempt wrote, then raised
    assert FETCHES == [2]  # ...but the parse still ran exactly once

    written = await client.pool.fetch(
        "SELECT sku, units FROM example_row WHERE batch = $1 ORDER BY sku", batch_ref
    )
    assert [(r["sku"], r["units"]) for r in written] == [("a-1", 2), ("b-2", 5)]


async def test_a_deadline_key_refuses_the_duplicate_request(
    client, unique_queue, batch_ref
):
    """The idempotency key a web handler builds from the request."""
    key = f"upload:{batch_ref}"

    first = await client.enqueue(
        "tests.test_examples_doc.ProcessUpload",
        queue=unique_queue,
        deadline_key=key,
        batch=batch_ref,
        raw=["a-1,2"],
    )
    assert first > 0

    with pytest.raises(asyncpg.UniqueViolationError):
        await client.enqueue(
            "tests.test_examples_doc.ProcessUpload",
            queue=unique_queue,
            deadline_key=key,
            batch=batch_ref,
            raw=["a-1,2"],
        )

    # the index is on (deadline_key, queue) WHERE state = 'queued', so the
    # same key in another queue is a different job...
    other = await client.enqueue(
        "tests.test_examples_doc.ProcessUpload",
        queue=f"{unique_queue}-other",
        deadline_key=key,
        batch=batch_ref,
        raw=["a-1,2"],
    )
    assert other != first

    # ...and once the first job leaves `queued` the key is free again: this
    # deduplicates concurrent submissions, it does not remember forever
    await client.pool.execute("UPDATE jorb SET state = 'finished' WHERE id = $1", first)
    again = await client.enqueue(
        "tests.test_examples_doc.ProcessUpload",
        queue=unique_queue,
        deadline_key=key,
        batch=batch_ref,
        raw=["a-1,2"],
    )
    assert again not in (first, other)


# ===========================================================================
# 2. ETL: a sequential pipeline that hands results forward
# ===========================================================================


class ExtractSales(Job):
    """Stage one: pull the day's rows (here, generate them)."""

    async def task(self, day: str, count: int = 4) -> dict[str, Any]:
        rows = await self.step(
            "fetch", lambda: [{"sku": f"sku-{i}", "units": i + 1} for i in range(count)]
        )
        return {"day": day, "rows": rows}


class TransformSales(Job):
    """Stage two: reads stage one's result out of ``upstream_result``."""

    async def task(self, upstream_result: dict[str, Any]) -> dict[str, Any]:
        rows = upstream_result["rows"]
        return {
            "day": upstream_result["day"],
            "rows": [r for r in rows if r["units"] > 1],
        }


class LoadWarehouse(Job):
    """Stage three: the write, so it lands exactly once."""

    async def task(self, batch: str, upstream_result: dict[str, Any]) -> dict[str, Any]:
        return await self.transaction("load", self.load, batch, upstream_result["rows"])

    async def load(
        self, conn: Any, batch: str, rows: list[dict[str, Any]]
    ) -> dict[str, Any]:
        for row in rows:
            await conn.execute(
                "INSERT INTO example_row (batch, sku, units) VALUES ($1, $2, $3)",
                batch,
                row["sku"],
                row["units"],
            )
        return {"loaded": len(rows)}


async def test_the_etl_pipeline_runs_in_order_and_passes_results(
    client, live_worker, unique_queue, app_tables, batch_ref
):
    extract = await client.enqueue(
        "tests.test_examples_doc.ExtractSales",
        queue=unique_queue,
        day="2026-07-01",
        count=4,
    )
    transform = await client.enqueue(
        "tests.test_examples_doc.TransformSales",
        queue=unique_queue,
        waitfor_job=extract,
        use_result_from=extract,
    )
    load = await client.enqueue(
        "tests.test_examples_doc.LoadWarehouse",
        queue=unique_queue,
        waitfor_job=transform,
        use_result_from=transform,
        batch=batch_ref,
    )

    # the two downstream stages start out blocked, not queued
    blocked = await client.pool.fetch(
        "SELECT state FROM jorb WHERE id = ANY($1::bigint[])", [transform, load]
    )
    assert {r["state"] for r in blocked} == {"waiting"}

    await live_worker()

    row = await wait_for_job_state(client.pool, load, ("finished",), timeout=30)
    assert row["result"] == {"loaded": 3}  # sku-0 had 1 unit and was filtered

    rows = await client.pool.fetch(
        "SELECT sku FROM example_row WHERE batch = $1 ORDER BY sku", batch_ref
    )
    assert [r["sku"] for r in rows] == ["sku-1", "sku-2", "sku-3"]


async def test_create_pipeline_chains_the_same_stages(
    client, live_worker, unique_queue
):
    """``create_pipeline()`` is the same chain when no result has to flow."""
    await live_worker()

    ids = await client.create_pipeline(
        [
            ("tests.test_examples_doc.ExtractSales", {"day": "2026-07-01"}),
            ("tests.test_examples_doc.ExtractSales", {"day": "2026-07-02"}),
            ("tests.test_examples_doc.ExtractSales", {"day": "2026-07-03"}),
        ],
        queue=unique_queue,
    )
    assert len(ids) == 3

    last = await wait_for_job_state(client.pool, ids[-1], ("finished",), timeout=30)
    assert last["result"]["day"] == "2026-07-03"

    # each stage really waited for the one before it
    rows = await client.pool.fetch(
        "SELECT id, waitfor_job, finished FROM jorb WHERE id = ANY($1::bigint[]) "
        "ORDER BY id",
        ids,
    )
    assert [r["waitfor_job"] for r in rows] == [None, ids[0], ids[1]]
    assert [r["finished"] for r in rows] == sorted(r["finished"] for r in rows)


# ===========================================================================
# 3. Fan-out / fan-in: many in parallel, then one summary
# ===========================================================================


class ResizeImage(Job):
    """One image, one size — the unit of the fan-out."""

    async def task(self, image: str, size: str) -> dict[str, Any]:
        return {"image": image, "size": size}


class BuildGallery(Job):
    """Fan-in: runs only once every resize in the group has finished."""

    async def task(self, batch: str, expected: int) -> dict[str, Any]:
        return {"batch": batch, "expected": expected}


async def test_the_gallery_waits_for_every_resize(
    client, live_worker, unique_queue, batch_ref
):
    await live_worker()

    items = [
        {"image": image, "size": size}
        for image in ("a.png", "b.png")
        for size in ("thumb", "small", "large")
    ]
    resize_ids, group_id = await client.create_fan_out(
        "tests.test_examples_doc.ResizeImage", items, queue=unique_queue
    )
    assert len(resize_ids) == 6

    gallery = await client.enqueue(
        "tests.test_examples_doc.BuildGallery",
        queue=unique_queue,
        waitfor_group=group_id,
        batch=batch_ref,
        expected=len(items),
    )
    assert (
        await client.pool.fetchval("SELECT state FROM jorb WHERE id=$1", gallery)
        == "waiting"
    )

    row = await wait_for_job_state(client.pool, gallery, ("finished",), timeout=30)
    assert row["result"] == {"batch": batch_ref, "expected": 6}

    # the gallery started only after the last resize finished
    last_resize_end = await client.pool.fetchval(
        "SELECT max(finished) FROM jorb WHERE id = ANY($1::bigint[])", resize_ids
    )
    assert row["started"] >= last_resize_end


async def test_the_two_dependency_edges_are_mutually_exclusive(client, unique_queue):
    """A job waits for one job or for one group, never for both."""
    with pytest.raises(ValueError, match="waitfor"):
        await client.enqueue(
            "tests.test_examples_doc.BuildGallery",
            queue=unique_queue,
            waitfor_job=1,
            waitfor_group=2,
            batch="x",
            expected=0,
        )


# ===========================================================================
# 4. The transactional outbox: the row and its job commit together
# ===========================================================================


class FulfillOrder(Job):
    """Enqueued from inside the transaction that created the order."""

    async def task(self, ref: str) -> dict[str, Any]:
        return {"fulfilled": ref}


async def test_the_order_and_its_job_commit_together(
    client, live_worker, unique_queue, app_tables, batch_ref
):
    await live_worker()

    async with client.pool.acquire() as conn, conn.transaction():
        await conn.execute(
            "INSERT INTO example_order (ref, cents) VALUES ($1, $2)", batch_ref, 1999
        )
        job_id = await JobClient.enqueue_in_transaction(
            conn,
            "tests.test_examples_doc.FulfillOrder",
            queue=unique_queue,
            ref=batch_ref,
        )

    row = await wait_for_job_state(client.pool, job_id, ("finished",), timeout=20)
    assert row["result"] == {"fulfilled": batch_ref}


async def test_a_rolled_back_order_leaves_no_job(
    client, unique_queue, app_tables, batch_ref
):
    """The half the outbox exists to prevent: a job for an order that isn't."""
    with pytest.raises(RuntimeError):
        async with client.pool.acquire() as conn, conn.transaction():
            await conn.execute(
                "INSERT INTO example_order (ref, cents) VALUES ($1, $2)",
                batch_ref,
                1999,
            )
            await JobClient.enqueue_in_transaction(
                conn,
                "tests.test_examples_doc.FulfillOrder",
                queue=unique_queue,
                ref=batch_ref,
            )
            raise RuntimeError("payment declined")

    assert (
        await client.pool.fetchval(
            "SELECT count(*) FROM example_order WHERE ref = $1", batch_ref
        )
        == 0
    )
    assert (
        await client.pool.fetchval(
            "SELECT count(*) FROM jorb WHERE kwargs->>'ref' = $1", batch_ref
        )
        == 0
    )


# ===========================================================================
# 5. A rate-limited third-party API
# ===========================================================================


class ChargeCards(Job):
    """Paces its calls to a rate-limited provider, one per second.

    The pause is ``self.sleep()``, so the job leaves the worker between
    calls instead of holding one for the whole run. Each charge is a
    ``step()``, so the retry after a provider error re-sends only the one
    that failed — and it still carries an idempotency key, because
    ``step()`` is at-least-once for anything outside this database.

    The loop is deterministic: its length comes from ``refs``, a checkpointed
    argument, so every attempt makes the same sequence of calls.
    """

    async def task(self, refs: list[str], cents: int) -> dict[str, Any]:
        for i, ref in enumerate(refs):
            if i:
                await self.sleep(1)  # the provider's rate limit, durably
            await self.step(f"charge-{ref}", self.charge, ref, cents)
        return {"charged": len(refs), "cents": cents}

    def charge(self, ref: str, cents: int) -> dict[str, Any]:
        CHARGES.append(ref)  # the provider dedupes on `ref`; we count calls
        if ref.endswith("-b") and self.job["error_count"] == 0:
            raise RuntimeError("provider returned 503")
        return {"ref": ref, "cents": cents}


async def test_the_pacing_releases_the_worker_and_charges_each_card_once(
    client, live_worker, unique_queue, batch_ref
):
    CHARGES.clear()
    await live_worker()

    refs = [f"{batch_ref}-a", f"{batch_ref}-b", f"{batch_ref}-c"]
    job_id = await client.enqueue(
        "tests.test_examples_doc.ChargeCards",
        queue=unique_queue,
        max_retries=3,
        initial_retry_delay=0,
        refs=refs,
        cents=1999,
    )

    # between calls the job is queued with a future run_after: it occupies
    # no worker and no connection while it waits out the rate limit
    for _ in range(80):
        row = await client.pool.fetchrow(
            "SELECT state, run_after > now() AS future FROM jorb WHERE id=$1", job_id
        )
        if row["state"] == "queued" and row["future"]:
            break
        await asyncio.sleep(0.1)
    assert row["state"] == "queued" and row["future"], dict(row)

    row = await wait_for_job_state(client.pool, job_id, ("finished",), timeout=40)
    assert row["result"] == {"charged": 3, "cents": 1999}
    assert row["error_count"] == 1  # the -b card's 503

    # -b was really re-sent; -a was NOT, because its step had committed
    assert [refs[0], refs[1], refs[1], refs[2]] == CHARGES


# ===========================================================================
# 6. Human in the loop: publish, wait, be told
# ===========================================================================


class AwaitRefundApproval(Job):
    """Publishes what it needs, then blocks on its mailbox."""

    async def task(self, ref: str, timeout: float = 25) -> dict[str, Any]:
        await self.set_event("awaiting", {"ref": ref})
        decision = await self.recv(topic="refund", timeout=timeout)
        return {"ref": ref, "approved": bool(decision and decision.get("ok"))}


async def test_an_operator_approves_a_waiting_job(
    client, live_worker, unique_queue, batch_ref
):
    await live_worker()

    job_id = await client.enqueue(
        "tests.test_examples_doc.AwaitRefundApproval",
        queue=unique_queue,
        tags={"ref": batch_ref, "needs": "approval"},
        ref=batch_ref,
    )

    # a dashboard finds it by tag, and reads what it is waiting for
    found = await client.search_jobs(tags={"needs": "approval"})
    assert job_id in [j["id"] for j in found]
    assert await client.get_event(job_id, "awaiting", timeout=10) == {"ref": batch_ref}

    await client.send_message(job_id, {"ok": True}, topic="refund")

    row = await wait_for_job_state(client.pool, job_id, ("finished",), timeout=30)
    assert row["result"] == {"ref": batch_ref, "approved": True}


# ===========================================================================
# 7. Batch import: enqueue thousands, watch the queue drain
# ===========================================================================


@job
class ImportRow(Job):
    """Registered, so the producer enqueues it with checked arguments."""

    async def task(self, sku: str, units: int) -> dict[str, Any]:
        return {"sku": sku, "units": units}


async def test_a_batch_enqueue_lands_every_row(client, live_worker, unique_queue):
    await live_worker()

    rows = [
        ("tests.test_examples_doc.ImportRow", {"sku": f"sku-{i}", "units": i})
        for i in range(200)
    ]
    ids = await client.enqueue_batch(rows, queue=unique_queue)
    assert len(ids) == 200
    assert len(set(ids)) == 200

    stats = await client.queue_stats(unique_queue)
    assert sum(stats.values()) == 200  # every row landed, whatever it is doing now

    # the typed enqueue catches a producer's typo before any INSERT
    with pytest.raises(TypeError):
        await ImportRow.enqueue(client, queue=unique_queue, sku="x", unts=1)


# ===========================================================================
# 8. Priority and capability routing
# ===========================================================================


async def test_a_lower_priority_number_is_claimed_first(
    client, live_worker, unique_queue
):
    """The direction that reads backwards until you have seen it once."""
    urgent = await client.enqueue(
        "tests.test_examples_doc.ResizeImage",
        queue=unique_queue,
        priority=10,
        image="urgent.png",
        size="thumb",
    )
    normal = await client.enqueue(
        "tests.test_examples_doc.ResizeImage",
        queue=unique_queue,
        priority=100,
        image="normal.png",
        size="thumb",
    )
    background = await client.enqueue(
        "tests.test_examples_doc.ResizeImage",
        queue=unique_queue,
        priority=900,
        image="background.png",
        size="thumb",
    )

    await live_worker()  # started AFTER the enqueues, so it sees all three

    for jid in (urgent, normal, background):
        await wait_for_job_state(client.pool, jid, ("finished",), timeout=30)

    order = await client.pool.fetch(
        "SELECT id, prio FROM jorb WHERE id = ANY($1::bigint[]) ORDER BY started",
        [urgent, normal, background],
    )
    assert [r["id"] for r in order] == [urgent, normal, background]
    assert [r["prio"] for r in order] == [10, 100, 900]


async def test_a_priority_above_the_ceiling_is_refused_at_enqueue(client, unique_queue):
    """The trap on the other end, closed where the caller can still see it.

    Workers claim ``prio <= their ceiling`` (1000 by default), so a job
    enqueued above that is not "low priority" -- it is unclaimable, and it
    would sit queued while every worker ignores it, with no error, no retry
    and no DLQ entry. The client refuses it instead, and says what to do.
    """
    with pytest.raises(ValueError) as refused:
        await client.enqueue(
            "tests.test_examples_doc.ResizeImage",
            queue=unique_queue,
            priority=5000,
            image="never.png",
            size="thumb",
        )
    message = str(refused.value)
    assert "priority 5000 is above the worker priority ceiling (1000)" in message
    assert "prio_ceiling=5000" in message  # and how to allow it deliberately

    # refused means NOT WRITTEN: no row to find later and wonder about
    assert (
        await client.pool.fetchval(
            "SELECT count(*) FROM jorb WHERE queue = $1", unique_queue
        )
        == 0
    )

    # exactly at the ceiling is fine, and is what "least urgent" means here
    at_ceiling = await client.enqueue(
        "tests.test_examples_doc.ResizeImage",
        queue=unique_queue,
        priority=1000,
        image="ok.png",
        size="thumb",
    )
    assert (
        await client.pool.fetchval("SELECT prio FROM jorb WHERE id=$1", at_ceiling)
        == 1000
    )


async def test_a_raised_ceiling_is_declared_by_the_client_and_the_worker(
    client, live_worker, unique_queue
):
    """A deployment that really runs high-ceiling workers says so twice.

    The ceiling is a WORKER setting the client cannot observe, so the client
    takes it as a declaration (``prio_ceiling=``) and the fleet takes it as a
    flag (``pj --max-prio``). Declaring it on the client alone does not make
    the job runnable -- only a worker at that ceiling claims it.
    """
    loud = JobClient(pool=client.pool, prio_ceiling=5000)
    low_urgency = await loud.enqueue(
        "tests.test_examples_doc.ResizeImage",
        queue=unique_queue,
        priority=5000,
        image="eventually.png",
        size="thumb",
    )

    # a default-ceiling worker is blind to it
    await live_worker()
    normal = await client.enqueue(
        "tests.test_examples_doc.ResizeImage",
        queue=unique_queue,
        priority=100,
        image="now.png",
        size="thumb",
    )
    await wait_for_job_state(client.pool, normal, ("finished",), timeout=20)
    assert (
        await client.pool.fetchval("SELECT state FROM jorb WHERE id=$1", low_urgency)
        == "queued"
    )

    # a worker whose ceiling covers it runs it
    await live_worker(prio=5000)
    await wait_for_job_state(client.pool, low_urgency, ("finished",), timeout=20)


async def test_a_capability_job_is_ignored_by_a_worker_without_it(
    client, live_worker, unique_queue
):
    """Routing: the GPU job waits until a GPU worker exists."""
    gpu_job = await client.enqueue(
        "tests.test_examples_doc.ResizeImage",
        queue=unique_queue,
        capability="gpu",
        image="a.png",
        size="large",
    )
    plain_job = await client.enqueue(
        "tests.test_examples_doc.ResizeImage",
        queue=unique_queue,
        image="b.png",
        size="large",
    )

    await live_worker(capabilities=("test",))  # no gpu
    await wait_for_job_state(client.pool, plain_job, ("finished",), timeout=20)
    assert (
        await client.pool.fetchval("SELECT state FROM jorb WHERE id=$1", gpu_job)
        == "queued"
    )

    await live_worker(capabilities=("test", "gpu"))
    await wait_for_job_state(client.pool, gpu_job, ("finished",), timeout=20)


# ===========================================================================
# 9. A recurring report, driven by the scheduler
# ===========================================================================


class DailyRevenueReport(Job):
    """The job a cron schedule creates; it reads its own schedule metadata."""

    async def task(self, region: str) -> dict[str, Any]:
        return {
            "region": region,
            "schedule": self.job["admin_data"].get("schedule_name"),
        }


async def test_a_schedule_creates_and_runs_its_job(
    client, live_worker, unique_queue, batch_ref
):
    """The whole path: define the schedule, let ``pj-scheduler`` fire it.

    The test backdates ``next_run`` and runs a single poll rather than
    waiting a real minute for the cron to come round; everything else — the
    deadline key, the admin_data, the created job — is what production does.
    """
    from pyjobby.admin_api import AdminAPI
    from pyjobby.scheduler import SchedulerWorker

    await live_worker()

    async with client.pool.acquire() as conn:
        schedule = await AdminAPI(conn).create_schedule(
            name=f"daily-revenue-{batch_ref}",
            job_class="tests.test_examples_doc.DailyRevenueReport",
            cron_expr="0 2 * * *",  # 02:00 every day...
            timezone="America/New_York",  # ...in Eastern wall-clock time
            queue=unique_queue,
            kwargs={"region": "emea"},
            max_concurrent_jobs=1,
            jitter_seconds=0,
            circuit_breaker_threshold=3,
            description="Daily revenue report at 2am Eastern",
        )
        assert schedule["next_run"] > utcnow()

        # force it due now instead of waiting for 02:00 Eastern
        await conn.execute(
            "UPDATE jorb_schedule SET next_run = now() - interval '1 minute' "
            "WHERE id = $1",
            schedule["id"],
        )

        worker = SchedulerWorker(conn, poll_interval=0.05)
        task = asyncio.create_task(worker.run())
        await asyncio.sleep(0.5)
        worker.stop()
        await asyncio.wait_for(task, timeout=5)

        after = await conn.fetchrow(
            "SELECT * FROM jorb_schedule WHERE id = $1", schedule["id"]
        )

    assert after["success_count"] == 1
    assert after["next_run"] > utcnow()  # advanced to the following 02:00

    job_id = await client.pool.fetchval(
        "SELECT id FROM jorb WHERE schedule_id = $1",
        schedule["id"],
    )
    row = await wait_for_job_state(client.pool, job_id, ("finished",), timeout=30)
    assert row["result"] == {
        "region": "emea",
        "schedule": f"daily-revenue-{batch_ref}",
    }
    # the deadline key is what makes a second scheduler instance a no-op
    assert row["deadline_key"].startswith(f"schedule:{schedule['id']}:")


# ===========================================================================
# 10. Waiting for an answer from the enqueuing process
# ===========================================================================


class Estimate(Job):
    """A short job whose caller wants the number back."""

    async def task(self, cents: int) -> dict[str, Any]:
        await self.set_event("progress", {"pct": 50})
        return {"total": cents * 2}


async def test_a_caller_can_wait_for_the_result(client, live_worker, unique_queue):
    await live_worker()

    handle = await client.enqueue_handle(
        "tests.test_examples_doc.Estimate", queue=unique_queue, cents=250
    )
    assert await handle.event("progress", timeout=15) == {"pct": 50}
    assert await handle.wait(timeout=20) == {"total": 500}
    assert await handle.status() == "finished"


class QuoteUnavailable(Job):
    """The other half of waiting: the job the caller was waiting on failed."""

    def task(self) -> None:
        raise ValueError("no price for that region")


async def test_a_dead_lettered_job_raises_at_the_waiter(
    client, live_worker, unique_queue
):
    await live_worker()

    handle = await client.enqueue_handle(
        "tests.test_examples_doc.QuoteUnavailable",
        queue=unique_queue,
        max_retries=1,
        initial_retry_delay=0,
    )

    with pytest.raises(JobFailedError, match="no price for that region"):
        await handle.wait(timeout=30)


# ===========================================================================
# The connection an admin call needs
# ===========================================================================


async def test_a_schedule_needs_a_connection_with_the_json_codecs(db_params, batch_ref):
    """Why the docs say ``pyjobby.db.connect``, not ``asyncpg.connect``.

    ``jorb_schedule.kwargs`` is JSONB. A bare asyncpg connection has no codec
    for it, so passing a dict fails at the INSERT -- the same trap that once
    made ``JobClient.enqueue()`` fail in production against a pool built
    without them.
    """
    from pyjobby import db as pyjobby_db
    from pyjobby.admin_api import AdminAPI

    bare = await asyncpg.connect(**db_params)
    try:
        with pytest.raises(asyncpg.DataError):
            await AdminAPI(bare).create_schedule(
                name=f"bare-{batch_ref}",
                job_class="tests.test_examples_doc.DailyRevenueReport",
                cron_expr="0 2 * * *",
                kwargs={"region": "emea"},
            )
    finally:
        await bare.close()

    equipped = await pyjobby_db.connect(**db_params)
    try:
        api = AdminAPI(equipped)
        schedule = await api.create_schedule(
            name=f"equipped-{batch_ref}",
            job_class="tests.test_examples_doc.DailyRevenueReport",
            cron_expr="0 2 * * *",
            kwargs={"region": "emea"},
        )
        assert schedule["kwargs"] == {"region": "emea"}
        # this connection is outside the test's transaction, so the row it
        # committed has to be removed by hand
        await api.delete_schedule(schedule["id"])
    finally:
        await equipped.close()
