-- ============================================================================
-- 003 -- jorb_history(at): make live-job history reachable by retention
-- ============================================================================
-- WHAT THIS IS. jorb_history is bounded by the job-retention cascade: when a
-- terminal job ages out, its history goes with it. A job that never
-- terminates — a parked durable state machine, which transitions
-- queued -> claimed -> running -> queued on every wake — writes roughly three
-- history rows per turn forever, and the cascade that bounds every other
-- child table never fires for it. The monitor now sweeps history rows past
-- the retention window by AGE, and this index is what lets that sweep walk
-- oldest-first and stop at its batch instead of scanning the largest table
-- in the system every cycle.
--
-- WHAT IT IS NOT is a file a fresh install ever executes: schema.sql already
-- contains the index, and migrate() RECORDS this version without running it.
-- tests/test_migrations.py holds the two paths together by requiring an
-- upgraded catalog to equal a fresh install's exactly.
--
-- IDEMPOTENCY IS A REQUIREMENT, NOT A COURTESY: IF NOT EXISTS makes running
-- this against a database that already has the index a no-op.
--
-- OPERATIONAL NOTE. The index build takes a write lock on jorb_history for
-- its duration (CREATE INDEX CONCURRENTLY cannot run inside a migration's
-- transaction). History is insert-only from triggers, so the lock delays
-- job-state transitions while it builds; on a large history table run the
-- migration in a quiet window.

CREATE INDEX IF NOT EXISTS jorb_history_at_idx ON jorb_history (at);
