"""Fault injectors and side-effect accounting for the durability suites.

Durability claims can only be tested by breaking things for real, so the
helpers here inject the failures a production deployment actually suffers:

* ``kill_backends`` terminates a worker's PostgreSQL backends server-side
  (``pg_terminate_backend``), which is indistinguishable from a database
  failover as far as the worker is concerned.
* ``sigkill_group`` hard-kills a real worker process group — no signal
  handler, no graceful shutdown, no registry deregistration, exactly like a
  machine losing power mid-step.
* ``age_worker_heartbeats`` fast-forwards the registry so the monitor's
  liveness grace period elapses without the test sleeping through it.

The ``jorb_test_effect`` helpers are the other half of the story: proving a
step "did not re-execute" needs an observable side effect OUTSIDE the
checkpoint table, so jobs append a row per real execution and tests compare
that count against the recorded checkpoints. The table is test-only (it is
not part of schema.sql), created on demand, and scoped by a ``tag`` (tests
pass their unique queue name) so parallel tests never see each other's rows.
"""

from __future__ import annotations

import asyncio
import contextlib
import os
import signal
import subprocess
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import asyncpg  # type: ignore[import-untyped]

# ---------------------------------------------------------------------------
# observable side effects (the "did this really execute?" ledger)
# ---------------------------------------------------------------------------

EFFECTS_DDL = """CREATE TABLE IF NOT EXISTS jorb_test_effect (
        id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tag    TEXT        NOT NULL,
        job_id BIGINT,
        label  TEXT        NOT NULL,
        at     TIMESTAMPTZ NOT NULL DEFAULT now()
    )"""


async def ensure_effects_table(conn: asyncpg.Connection | asyncpg.Pool) -> None:
    """Create the side-effect ledger if it does not exist yet.

    Also drops rows older than an hour so a long-lived test database does not
    accumulate them (tests scope their assertions by ``tag`` regardless)."""
    await conn.execute(EFFECTS_DDL)
    await conn.execute("DELETE FROM jorb_test_effect WHERE at < now() - interval '1 h'")


async def record_effect(
    conn: asyncpg.Connection | asyncpg.Pool, tag: str, job_id: int, label: str
) -> int:
    """Append one real execution to the ledger; returns its unique id.

    Called from inside job code (through the worker's own connection), so the
    row exists exactly as often as the code actually ran — no matter what the
    checkpoint table says."""
    effect_id: int = await conn.fetchval(
        """INSERT INTO jorb_test_effect (tag, job_id, label)
           VALUES ($1, $2, $3) RETURNING id""",
        tag,
        job_id,
        label,
    )
    return effect_id


async def count_effects(
    conn: asyncpg.Connection | asyncpg.Pool, tag: str, label: str | None = None
) -> int:
    """How many real executions were recorded for this tag (and label)."""
    total: int = await conn.fetchval(
        """SELECT count(*) FROM jorb_test_effect
           WHERE tag = $1 AND ($2::text IS NULL OR label = $2)""",
        tag,
        label,
    )
    return total


async def effect_counts(
    conn: asyncpg.Connection | asyncpg.Pool, tag: str
) -> dict[str, int]:
    """``{label: executions}`` for this tag — for exact-value assertions."""
    rows = await conn.fetch(
        """SELECT label, count(*) AS n FROM jorb_test_effect
           WHERE tag = $1 GROUP BY label""",
        tag,
    )
    return {r["label"]: r["n"] for r in rows}


async def effect_counts_per_job(
    conn: asyncpg.Connection | asyncpg.Pool, tag: str
) -> dict[tuple[int, str], int]:
    """``{(job_id, label): executions}`` for this tag."""
    rows = await conn.fetch(
        """SELECT job_id, label, count(*) AS n FROM jorb_test_effect
           WHERE tag = $1 GROUP BY job_id, label""",
        tag,
    )
    return {(r["job_id"], r["label"]): r["n"] for r in rows}


# ---------------------------------------------------------------------------
# database-level fault injection
# ---------------------------------------------------------------------------


async def backend_pids(pool: asyncpg.Pool) -> set[int]:
    """Server-side pids of every other backend on this test database."""
    rows = await pool.fetch(
        """SELECT pid FROM pg_stat_activity
           WHERE datname = current_database() AND pid <> pg_backend_pid()"""
    )
    return {r["pid"] for r in rows}


@asynccontextmanager
async def new_backends(pool: asyncpg.Pool) -> AsyncIterator[list[int]]:
    """Collect the backends that appear while the block runs.

    Diffing pg_stat_activity around a worker's startup identifies exactly
    that worker's connections — no application_name plumbing required, and it
    fails loudly (the caller asserts the count) if anything else connects at
    the same time. The yielded list is filled in when the block exits.
    """
    before = await backend_pids(pool)
    found: list[int] = []
    try:
        yield found
    finally:
        found.extend(sorted(await backend_pids(pool) - before))


async def kill_backends(
    pool: asyncpg.Pool, pids: list[int] | set[int], timeout: float = 10.0
) -> int:
    """Terminate the given backends; returns how many actually died.

    Waits until they are gone from pg_stat_activity, so when this returns the
    failure has really landed on the victim process."""
    killed = 0
    for pid in pids:
        if await pool.fetchval("SELECT pg_terminate_backend($1)", pid):
            killed += 1

    deadline = asyncio.get_running_loop().time() + timeout
    while asyncio.get_running_loop().time() < deadline:
        if not await backend_pids(pool) & set(pids):
            return killed
        await asyncio.sleep(0.05)
    raise AssertionError(f"backends {sorted(pids)} still present after {timeout}s")


# ---------------------------------------------------------------------------
# process-level fault injection
# ---------------------------------------------------------------------------


def sigkill_group(proc: subprocess.Popen[bytes], grace: float = 10.0) -> int:
    """SIGKILL a spawned daemon's whole process group and reap it.

    No SIGTERM first: the worker's graceful-shutdown handler must never run,
    so nothing deregisters from jorb_worker and no terminal state is written
    — the failure mode the monitor's dead-worker sweep exists for. The
    launcher forks its workers into the same group, so the group kill takes
    the children too.

    Returns the launcher's exit status (-9 for SIGKILL)."""
    with contextlib.suppress(ProcessLookupError, PermissionError):
        os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
    proc.wait(timeout=grace)
    return int(proc.returncode)


def write_worker_config(tmp_path: Path, db_params: dict[str, Any]) -> Path:
    """Write a pyjobby.conf.py for the real ``pj`` launcher and return it."""
    config = tmp_path / "pyjobby.conf.py"
    config.write_text(
        "db_params = {\n"
        f"    'host': {db_params['host']!r},\n"
        f"    'port': {db_params['port']!r},\n"
        f"    'user': {db_params['user']!r},\n"
        f"    'password': {db_params['password']!r},\n"
        f"    'database': {db_params['database']!r},\n"
        "}\n"
        "web_listen = None\n"
    )
    return config


# ---------------------------------------------------------------------------
# clock fault injection (skip the monitor's grace periods)
# ---------------------------------------------------------------------------


async def age_worker_heartbeats(
    pool: asyncpg.Pool, queue: str, seconds: float = 300
) -> str:
    """Backdate ``jorb_worker.last_seen`` for a queue's workers.

    Lets a test reach the monitor's liveness grace period without waiting it
    out in real time. Returns the UPDATE status string so callers can assert
    exactly how many registry rows were aged."""
    status: str = await pool.execute(
        """UPDATE jorb_worker SET last_seen = now() - make_interval(secs => $2)
           WHERE queue = $1 AND shutdown_at IS NULL""",
        queue,
        seconds,
    )
    return status


async def age_claim(pool: asyncpg.Pool, job_id: int, seconds: float) -> str:
    """Backdate ``jorb.updated`` so an unregistered claim looks abandoned."""
    status: str = await pool.execute(
        """UPDATE jorb SET updated = now() - make_interval(secs => $2)
           WHERE id = $1""",
        job_id,
        seconds,
    )
    return status
